In [2]:
import numpy as np 
import pandas as pd

## 1-D Array

In [3]:
my_list =[11, 13, 15]
my_list                  # [11, 13, 15]
np.array([11, 13, 15])   # array([11, 13, 15])

array([11, 13, 15])

In [4]:
x = np.array([11, 13, 15])
x.shape

(3,)

In [5]:
x[1]
type(x) # numpy.ndarray
type(my_list) # list

list

In [6]:
print(type(x.shape)) # this will be a tuple
print(len(x.shape)) # this will show length of the tuple

<class 'tuple'>
1


In [7]:
a = (3, 4)
print(type(a)) # tuple
print(len(a)) # 2

<class 'tuple'>
2


## 2-D Arrays

In [8]:
my_2d_list = [ [1,2] , [3,4] , [5,6] ] 
my_2d_list

[[1, 2], [3, 4], [5, 6]]

In [9]:
y = np.array(my_2d_list)
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
# We can access using index
y[2]   # [5, 6] 
y[0,0] # y[0][0]   same result: 1
y[2,1] # y[2][1]   same result: 6

np.int64(6)

In [12]:
# Create a 2-d array with data 

z = [[10,20,30,40],
      [50, 60, 70, 80],
      [90, 100, 110, 120]] 


z[1][3] # 80

80

In [13]:
# Create a 3-d array with data

m = [
    
    [[1,2,3],
     [4,5,6]],
    
      [[10,20,30],
      [40,50,60]],
    
     [[100,200,300],
      [400,500,600]]
]

assert m[0][0][0] == 1
assert m[1][1][0] == 40
assert m[0][0][1] == 2
assert m[2][1][2] == 600

In [14]:
# Crud - create, read, update, delete  ---- we created lists above already 


# -------- read
# Accessing a row 
# my_2d_list = [ [1,2] , [3,4] , [5,6]] 

my_2d_list[:][2] # [5, 6]
my_2d_list[2][0] # 5
m[-2:-1][0] # [[10, 20, 30], [40, 50, 60]]
my_2d_list[:][0] # [1, 2]

[1, 2]

In [15]:
# -------- update

my_2d_list[2][1] = 444
my_2d_list

[[1, 2], [3, 4], [5, 444]]

In [16]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[7, 8]])
arr3 = np.append(arr1, arr2) # It returns a new array. It doesn't add arr2 to arr1.
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
print(arr3.shape) # Will get (8,)
arr4 = arr3.reshape(4, 2) # It doesn't change arr3, but use data to make a new array
print(arr3)
print('---')
print(arr4)

(8,)
[1 2 3 4 5 6 7 8]
---
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
# delete - we cannot delete existing items
# np.delete(array, index, axis)
# axis 0 is along rows, axis 1 is along the columns

arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

# we want to delete row [5,6], it is in row 2 axis 0

arr2 = np.delete(arr1, 2, 0)
arr2

array([[1, 2],
       [3, 4],
       [7, 8]])

In [19]:
# delete column 2 4 6 8
arr3 = np.delete(arr1, 1, 1)
arr3

array([[1],
       [3],
       [5],
       [7]])

In [20]:
print(arr1)
print('---')
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
---
[[1]
 [3]
 [5]
 [7]]


## Some Useful Functions

In [21]:
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr2 = np.arange(0, 10, 4)
arr2

array([0, 4, 8])

In [23]:
arr3 = np.zeros(3)
arr4 = np.zeros((3,4))
arr5 = np.ones((3,4))
arr6 = np.identity(3)
print(arr3)
print('---------------')
print(arr4)
print('---------------')
print(arr5)
print('---------------')
print(arr6)

[0. 0. 0.]
---------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
---------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
---------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
arr7 = np.eye(3)
arr8 = np.eye(5, k=1)

print(arr7)
print(arr8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [25]:
arr9 = np.random.rand(3, 2)
arr9

p = np.random.randint(0, 100, 30) # range of 0 to 100, 30 numbers in the array
p

array([91, 90, 28, 18, 48, 14,  0, 81, 32, 31, 68, 68, 61, 95, 83, 68, 80,
       24, 50, 47, 14,  8, 95, 48, 65, 37, 61, 45, 26, 13])

In [26]:
p.reshape(2,15)
p

array([91, 90, 28, 18, 48, 14,  0, 81, 32, 31, 68, 68, 61, 95, 83, 68, 80,
       24, 50, 47, 14,  8, 95, 48, 65, 37, 61, 45, 26, 13])

In [27]:
p.min() # 1
p.max() # 98
p.argmin() # indice of the minimum number 
p.argmax() # indice of the maximum number

np.int64(13)

## Operations with matrices

In [28]:
a = [1, 3, 5]
b = [20, 30 , 40]
a + b 

[1, 3, 5, 20, 30, 40]

In [29]:
d = np.array([1, 3, 5])
e = np.array([10, 100, 1000])
d + e

array([  11,  103, 1005])

In [30]:
# if the dimensions are not the same, we get an error message
d = np.array([1, 3, 5])
e = np.array([10, 100, 1000, 10000])
d + e

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
f = np.array(["ha", "ho"])
g = np.array(["hey", "how"])
h = np.append(f, g)
h

## multiply 

## Multiply with the matrix

In [ ]:
m = np.array([1,2,3])
m*2

array([2, 4, 6])

In [ ]:
[2,4,6] * 3 #since its not written as an array anymore, the output changes

[2, 4, 6, 2, 4, 6, 2, 4, 6]

In [ ]:
i = np.array([1,2,3,4])
i*i

array([ 1,  4,  9, 16])

In [ ]:
[1,  4,  9, 16] * [1,  4,  9, 16] # type error 

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
[1,  4,  9, 16] * 2

[1, 4, 9, 16, 1, 4, 9, 16]

# Pandas

## 1. Pandas - Series


In [ ]:
name = ["Abby", "Dylan", "Hope"]
num = [12, 15, 13]
num_arr = np.array(num)
dct = {"Abby" : 12, "Dylan" : 15, "Hope" : 13}

In [ ]:
series1 = pd.Series(num)
series1

0    12
1    15
2    13
dtype: int64

In [ ]:
series1 = pd.Series(num, index = name)
series1

Abby     12
Dylan    15
Hope     13
dtype: int64

In [ ]:
series1.shape

(3,)

In [ ]:
# we can also create a series from a numpy array
series2 = pd.Series(num_arr, name) 
series2

Abby     12
Dylan    15
Hope     13
dtype: int64

In [ ]:
# we can create a series from a dictionary
series3 = pd.Series(dct)
series3

Abby     12
Dylan    15
Hope     13
dtype: int64

In [ ]:
lst = [2.45, 3.67, 4.97]
lst_s = pd.Series(lst)
print(lst_s)
print(lst_s[0]) # 2.45
print(lst_s[2]) # 4.97

0    2.45
1    3.67
2    4.97
dtype: float64
2.45
4.97


In [ ]:
s5 = pd.Series([22, 33, 44], ['One', 'Two', 'Three']) # (data, index)
s5

One      22
Two      33
Three    44
dtype: int64

In [ ]:
# another way to access the data is through the named index itself
print(s5['One'])
print(s5['Three'])

22
44


In [ ]:
s77 = pd.Series(data=[22, 25, 27] , index=[5, 7, 9])
print(s77)
print(s77[5])
print(s77[0]) # Key error since Pandas thinks that [0] is an index and we dont have that index name

5    22
7    25
9    27
dtype: int64
22


KeyError: 0

In [ ]:
# to access a position without using the index name
print(s77.iloc[0]) # use iloc[] instead 
print(s77.iloc[1])

In [ ]:
s8 = pd.Series([22, 25, 27], ['H', 'A', 'Y'])
s8

In [ ]:
# changing the value 
s8['H'] = 23 
s8

NameError: name 's8' is not defined

In [ ]:
# appending a value
s8['S'] = 29
s8['E'] = 31
s8

NameError: name 's8' is not defined

In [ ]:
s9 = s8.drop(['S', 'E']) # s8.drop(labels = ['S', 'E'])
print(s8)
print('---------------')
print(s9)

NameError: name 's8' is not defined

In [ ]:
# Operations 

s1 = pd.Series([11,22,33])
s2 = pd.Series([11,22,33])
s1 + s2

0    22
1    44
2    66
dtype: int64

In [ ]:
# Adds the value in accordance with the name of the index itself, 
# which is why we have no values for 'C' and 'D' since only one of the series contains the letters while both s3 and s4 have 'A' and 'B'
s3 = pd.Series([11,22,33], ['A', 'B', 'C'])
s4 = pd.Series([11,22,33], ['B', 'D', 'A'])
s3 + s4

A    44.0
B    33.0
C     NaN
D     NaN
dtype: float64

## Pandas - DataFrame

In [ ]:
df = pd.DataFrame({
    'Gold' : [15, 20,15],
    'Silver' : [ 22, 66, 7],
    'Bronze' : [23, 2, 23],
    'Continent' : ['Europe', 'Asia', 'Asia']
     }, 
     [ 'France' , 'Thailand' , 'Vietnam'])

df
                  

Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20      66       2      Asia
Vietnam     15       7      23      Asia

In [ ]:
# we can create them separately as well 
my_dt = {
    'Gold' : [15, 20,15],
    'Silver' : [ 22, 66, 7],
    'Bronze' : [23, 2, 23],
    'Continent' : ['Europe', 'Asia', 'Asia']}

my_dt2 = ['France' , 'Thailand' , 'Vietnam']

df = pd.DataFrame(my_dt, my_dt2)
df

Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20      66       2      Asia
Vietnam     15       7      23      Asia

In [ ]:
# Create a dataframe by manually setting each column with a series.
df3 = pd.DataFrame()
ser1 = pd.Series([15, 20, 15])
ser2 = pd.Series([22, 66, 7])
ser3 = pd.Series([23, 2, 23])
ser4 = pd.Series(['Europe', 'Asia', 'Asia'])

df3['Gold'] = ser1
df3['Silver'] = ser2
df3['Bronze'] = ser3
df3['Continent'] = ser4

df3 

Gold  Silver  Bronze Continent
0    15      22      23    Europe
1    20      66       2      Asia
2    15       7      23      Asia

In [ ]:
# what about the index?

my_ind = pd.Series(['France', 'Thailand', 'Vietnam'])

df33 = df3.set_index(my_ind) 
print(df33)
print('----------------------')
print(df3)


          Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20      66       2      Asia
Vietnam     15       7      23      Asia
----------------------
   Gold  Silver  Bronze Continent
0    15      22      23    Europe
1    20      66       2      Asia
2    15       7      23      Asia


In [ ]:
# still, if we call df3, it will show us the dataframe with no index naming. Hence, we use inplace = True to make permanent changes
df3.set_index(my_ind, inplace = True)
df3

Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20      66       2      Asia
Vietnam     15       7      23      Asia

In [ ]:
# Now, if we print both df3 and df33, we get the same result 
print(df33)
print('----------------------')
print(df3)

          Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20      66       2      Asia
Vietnam     15       7      23      Asia
----------------------
          Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20      66       2      Asia
Vietnam     15       7      23      Asia


## Reading - subsetting columns, subsetting rows, acessing any particular element

In [ ]:
# accessing 
df['Continent'] # df['Continent'] -> pandas.core.series.Series

France      Europe
Thailand      Asia
Vietnam       Asia
Name: Continent, dtype: object

In [ ]:
# accessing 
df[['Continent']] # df['Continent'] -> pandas.core.series.Dataframe

Continent
France      Europe
Thailand      Asia
Vietnam       Asia

In [ ]:
df[['Gold' , 'Continent']] 

Gold Continent
France      15    Europe
Thailand    20      Asia
Vietnam     15      Asia

In [ ]:
# subsetting rows
df.loc[0] # since our dataframe has countries as index and not [0,1,2], shows key error


KeyError: 0

In [ ]:
# which is why we use iloc instead 
df.iloc[0] # returns a series
df.iloc[[0]] # returns a dataframe

In [ ]:
df.iloc[1:3] #df.loc[1:3] wont work


In [ ]:
df.loc['Thailand'] # since now we used the name of our index, it works! - shows in series

In [ ]:
df.loc[['Thailand']] # - shows in dataframe
df.loc[['Thailand', 'France']]

Gold  Silver  Bronze Continent
Thailand    20      66       2      Asia
France      15      22      23    Europe

In [ ]:
# Both rows and columns
df.iloc[2, 0:2] # 2nd row, first two columns but in series
df.iloc[[2], 0:2] # same but in datafram

Gold  Silver
Vietnam    15       7

In [ ]:
df.iloc[:,:] # all rows, all columns
df.iloc[:,1:-1] # all columns excceot the zeroth and the last
df.iloc[:2, [0,3]] # only the 0th and 3rd column
df.iloc[:2, :] # only the 0th and 1st row and all columns

Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20      66       2      Asia

In [ ]:
x = df.iloc[2]
x # type - series

Gold           15
Silver          7
Bronze         23
Continent    Asia
Name: Vietnam, dtype: object

In [ ]:
x.iloc[1, 2] # IndexError: too many indexes

IndexingError: Too many indexers

In [ ]:
x.iloc[2] # type - numpy.int64

np.int64(23)

In [ ]:
x.iloc[[2]] # type - series 

Bronze    23
Name: Vietnam, dtype: object

In [ ]:
x.iloc[[2], [2]] # Indexing Error

IndexingError: Too many indexers

In [ ]:
df.iloc[2,1] # 2nd row, 1st column number -->  7 (keep in mind: its a comma, not , 
df.iloc[2] # 2nd row but in series 

Gold           15
Silver          7
Bronze         23
Continent    Asia
Name: Vietnam, dtype: object

In [ ]:
# How to update values
# using iloc
df.iloc[2,2] = 17 # updates df[2nd row, 2nd column] to be 17
df

Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20      66       2      Asia
Vietnam     15       7      17      Asia

In [ ]:
# using iloc
df.loc['Thailand', 'Silver'] = 8
df # here, we used loc instead to access the index 

Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20       8       2      Asia
Vietnam     15       7      17      Asia

In [ ]:
# appending
dfplus = pd.DataFrame(
    {
        'Gold' : [5],
        'Silver' : [2],
        'Bronze' : [8],
        'Continent' : ['Europe']
    },
    ['England'])
dfplus

Gold  Silver  Bronze Continent
England     5       2       8    Europe

In [ ]:
df3 = pd.concat([df, dfplus])
df3

Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20       8       2      Asia
Vietnam     15       7      17      Asia
England      5       2       8    Europe

In [ ]:
df # stays the same

Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20       8       2      Asia
Vietnam     15       7      17      Asia

In [ ]:
df3['Abbreviation'] = pd.Series(['FR', 'TH' , 'CN', 'UK'], index = df3.index)
df3

Gold  Silver  Bronze Continent Abbreviation
France      15      22      23    Europe           FR
Thailand    20       8       2      Asia           TH
Vietnam     15       7      17      Asia           CN
England      5       2       8    Europe           UK

In [ ]:
df3['Abbreviation'] = pd.Series(['FR', 'TH' , 'CN', 'UK'])
df3 # Nan values only

Gold  Silver  Bronze Continent Abbreviation
France      15      22      23    Europe          NaN
Thailand    20       8       2      Asia          NaN
Vietnam     15       7      17      Asia          NaN
England      5       2       8    Europe          NaN

In [ ]:
# Delete rows
df3 = df3.drop("England")
df3

Gold  Silver  Bronze Continent Abbreviation
France      15      22      23    Europe          NaN
Thailand    20       8       2      Asia          NaN
Vietnam     15       7      17      Asia          NaN

In [ ]:
# preserve a copy if you wanna make changes
df4 = df3.copy()
df4

Gold  Silver  Bronze Continent Abbreviation
France      15      22      23    Europe          NaN
Thailand    20       8       2      Asia          NaN
Vietnam     15       7      17      Asia          NaN

In [ ]:
# axis 0 -> rows
# axis 1 -> columns

df4.drop("France", inplace = True)
df4

Gold  Silver  Bronze Continent Abbreviation
Thailand    20       8       2      Asia          NaN
Vietnam     15       7      17      Asia          NaN

In [ ]:
df5 = df.copy()
df5

Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20       8       2      Asia
Vietnam     15       7      17      Asia

In [ ]:
df5 = df5.drop('Thailand', axis = 0)
# wont work on axis = 1 since 'Thailand'is a row name and not a column name 
df5 = df5.drop('Silver', axis= 1)
df5

Gold  Bronze Continent
France     15      23    Europe
Vietnam    15      17      Asia

In [ ]:
df # remains the same

Gold  Silver  Bronze Continent
France      15      22      23    Europe
Thailand    20       8       2      Asia
Vietnam     15       7      17      Asia

In [ ]:
# for columns
df6 = df.copy()
df6.drop('Gold', axis = 1, inplace = True)
df6

Silver  Bronze Continent
France        22      23    Europe
Thailand       8       2      Asia
Vietnam        7      17      Asia

In [ ]:
df7 = df.copy()
df7.drop("France", inplace=True)
df7

Gold  Silver  Bronze Continent
Thailand    20       8       2      Asia
Vietnam     15       7      17      Asia

# Data Manipulation

In [ ]:
df1 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/muic1.csv")
df2 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/muic2.csv")
df3 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/muic3.csv")

In [ ]:
df1

ID            Name  Major  GPA
0  6780001      Ann Molive   ICCH  3.2
1  6780002      Ben Kenobi   ICJD  NaN
2  6780003   Peter Cruiser   ICBA  3.3
3  6780004      Bob Hanger   ICFS  3.5
4  6780005        Moe Otto   ICCS  3.1

In [ ]:
df2

ID         Name  Major  GPA
0  6780031      Tom Lee   ICCS  2.7
1  6780032     Pat Cade   ICFS  3.8
2  6780033   Will Power   ICBA  2.7
3  6780034   Arty Didas   ICFS  3.2
4  6780035    Bart Yolo   ICCS  1.7

In [ ]:
df3

ID               Name  Major  GPA
0  6780021         Terry Cuda   ICCS  1.9
1  6780022        Justin Bull   ICBA  2.8
2  6780023       Ed Cheerbeer   ICCS  4.0
3  6780024          Luke Warm   ICCS  1.2
4  6780025   Anakin Skywalker   ICJD  NaN

In [ ]:
row_concat1 = pd.concat([df1, df2, df3])
row_concat1.shape

(15, 4)

In [ ]:
row_concat1

ID               Name  Major  GPA
0  6780001         Ann Molive   ICCH  3.2
1  6780002         Ben Kenobi   ICJD  NaN
2  6780003      Peter Cruiser   ICBA  3.3
3  6780004         Bob Hanger   ICFS  3.5
4  6780005           Moe Otto   ICCS  3.1
0  6780031            Tom Lee   ICCS  2.7
1  6780032           Pat Cade   ICFS  3.8
2  6780033         Will Power   ICBA  2.7
3  6780034         Arty Didas   ICFS  3.2
4  6780035          Bart Yolo   ICCS  1.7
0  6780021         Terry Cuda   ICCS  1.9
1  6780022        Justin Bull   ICBA  2.8
2  6780023       Ed Cheerbeer   ICCS  4.0
3  6780024          Luke Warm   ICCS  1.2
4  6780025   Anakin Skywalker   ICJD  NaN

In [ ]:
# we want to subset the 4th student out 
row_concat1.loc[3]
# but there are many rows in index 3 since they all match the label

ID         Name  Major  GPA
3  6780004   Bob Hanger   ICFS  3.5
3  6780034   Arty Didas   ICFS  3.2
3  6780024    Luke Warm   ICCS  1.2

In [ ]:
# to get the 4th row, we use iloc since iloc is the integer location
row_concat1.iloc[[3]] # [3] for dataframe

ID         Name  Major  GPA
3  6780004   Bob Hanger   ICFS  3.5

In [ ]:
# getting a better index
row_concat2 = pd.concat([df1, df2, df3], ignore_index = True)
row_concat2

ID               Name  Major  GPA
0   6780001         Ann Molive   ICCH  3.2
1   6780002         Ben Kenobi   ICJD  NaN
2   6780003      Peter Cruiser   ICBA  3.3
3   6780004         Bob Hanger   ICFS  3.5
4   6780005           Moe Otto   ICCS  3.1
5   6780031            Tom Lee   ICCS  2.7
6   6780032           Pat Cade   ICFS  3.8
7   6780033         Will Power   ICBA  2.7
8   6780034         Arty Didas   ICFS  3.2
9   6780035          Bart Yolo   ICCS  1.7
10  6780021         Terry Cuda   ICCS  1.9
11  6780022        Justin Bull   ICBA  2.8
12  6780023       Ed Cheerbeer   ICCS  4.0
13  6780024          Luke Warm   ICCS  1.2
14  6780025   Anakin Skywalker   ICJD  NaN

### Adding a dataframe where columns are not identical


In [ ]:
# Case 1: A subset
narrower_df = pd.DataFrame({
    "ID" : [6781111, 6781112],
    "Name" : ["Jacky Chow", "Jet Loo"]
})
narrower_df

ID        Name
0  6781111  Jacky Chow
1  6781112     Jet Loo

In [ ]:
# Major and GPA show NaN values 
dfx = pd.concat([df1, narrower_df])
dfx

ID            Name  Major  GPA
0  6780001      Ann Molive   ICCH  3.2
1  6780002      Ben Kenobi   ICJD  NaN
2  6780003   Peter Cruiser   ICBA  3.3
3  6780004      Bob Hanger   ICFS  3.5
4  6780005        Moe Otto   ICCS  3.1
0  6781111      Jacky Chow    NaN  NaN
1  6781112         Jet Loo    NaN  NaN

In [ ]:
# Case 2: creating a dataframe with totally different columns
another_df = pd.DataFrame({
    "Hobby" : ["Reading", "Running"],
    "Club" : ["Board Game", "Debate"]
})
another_df

Hobby        Club
0  Reading  Board Game
1  Running      Debate

In [ ]:
dfy = pd.concat([df1, another_df])
dfy

ID            Name  Major  GPA    Hobby        Club
0  6780001.0      Ann Molive   ICCH  3.2      NaN         NaN
1  6780002.0      Ben Kenobi   ICJD  NaN      NaN         NaN
2  6780003.0   Peter Cruiser   ICBA  3.3      NaN         NaN
3  6780004.0      Bob Hanger   ICFS  3.5      NaN         NaN
4  6780005.0        Moe Otto   ICCS  3.1      NaN         NaN
0        NaN             NaN    NaN  NaN  Reading  Board Game
1        NaN             NaN    NaN  NaN  Running      Debate

In [ ]:
# case 3: some columns are the same
foo_df = pd.DataFrame({
    "ID" : [6780101, 6780102],
    "Major" : ["ICCH", "ICCS"],
    "Height" : [65, 59],
    "Weight" : [170, 180]})
foo_df

ID Major  Height  Weight
0  6780101  ICCH      65     170
1  6780102  ICCS      59     180

In [ ]:
dfz = pd.concat([df1, foo_df])
dfz

ID            Name  Major  GPA  Height  Weight
0  6780001      Ann Molive   ICCH  3.2     NaN     NaN
1  6780002      Ben Kenobi   ICJD  NaN     NaN     NaN
2  6780003   Peter Cruiser   ICBA  3.3     NaN     NaN
3  6780004      Bob Hanger   ICFS  3.5     NaN     NaN
4  6780005        Moe Otto   ICCS  3.1     NaN     NaN
0  6780101             NaN   ICCH  NaN    65.0   170.0
1  6780102             NaN   ICCS  NaN    59.0   180.0

In [ ]:
# inner join - is structural - looks for columns that are in both the dataframes
dfz = pd.concat([df1, foo_df], join = "inner")
dfz

ID  Major
0  6780001   ICCH
1  6780002   ICJD
2  6780003   ICBA
3  6780004   ICFS
4  6780005   ICCS
0  6780101   ICCH
1  6780102   ICCS

In [ ]:
# lets give our 0th index a nan value in major 
df1.loc[0, "Major"] = np.nan
df1

ID            Name  Major  GPA
0  6780001      Ann Molive    NaN  3.2
1  6780002      Ben Kenobi   ICJD  NaN
2  6780003   Peter Cruiser   ICBA  3.3
3  6780004      Bob Hanger   ICFS  3.5
4  6780005        Moe Otto   ICCS  3.1

In [ ]:
# concat is based on structure and not values
dfz = pd.concat([df1, foo_df], join = "inner")
dfz

ID  Major
0  6780001    NaN
1  6780002   ICJD
2  6780003   ICBA
3  6780004   ICFS
4  6780005   ICCS
0  6780101   ICCH
1  6780102   ICCS

In [ ]:
# outer - default value of the concat function, 
# leaving it blank is the same as setting join = "outer"
dfz = pd.concat([df1, foo_df], join = "outer")
dfz

ID            Name  Major  GPA  Height  Weight
0  6780001      Ann Molive    NaN  3.2     NaN     NaN
1  6780002      Ben Kenobi   ICJD  NaN     NaN     NaN
2  6780003   Peter Cruiser   ICBA  3.3     NaN     NaN
3  6780004      Bob Hanger   ICFS  3.5     NaN     NaN
4  6780005        Moe Otto   ICCS  3.1     NaN     NaN
0  6780101             NaN   ICCH  NaN    65.0   170.0
1  6780102             NaN   ICCS  NaN    59.0   180.0

### Adding Columns

In [ ]:
# download our other files for the next tasks

df1 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_1.csv")
df2 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_2.csv")
df3 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_3.csv")

In [ ]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [ ]:
df3

A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [ ]:
row_concat = pd.concat([df1, df2, df3])
row_concat

A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [ ]:
# if we want to add along the column, use axis = 1
col_concat = pd.concat([df1, df2, df3], axis = 1)
col_concat

A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [ ]:
col_concat['A'] # gets all the A's columns

A   A    A
0  A0  A4   A8
1  A1  A5   A9
2  A2  A6  A10
3  A3  A7  A11

In [ ]:
# adding columns with different indexes
df1.columns = ['A', 'B', 'C', 'D']
df2.columns = ['D', 'E', 'F', 'G']
df3.columns = ['A', 'D', 'G', 'H']

In [ ]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

D   E   F   G
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [ ]:
df3

A    D    G    H
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [ ]:
# all DataFrames have column D and hence, there is not a single NaN value there
row_concat = pd.concat([df1, df2, df3])
row_concat

A    B    C    D    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN   A4   B4   C4   D4  NaN
1  NaN  NaN  NaN   A5   B5   C5   D5  NaN
2  NaN  NaN  NaN   A6   B6   C6   D6  NaN
3  NaN  NaN  NaN   A7   B7   C7   D7  NaN
0   A8  NaN  NaN   B8  NaN  NaN   C8   D8
1   A9  NaN  NaN   B9  NaN  NaN   C9   D9
2  A10  NaN  NaN  B10  NaN  NaN  C10  D10
3  A11  NaN  NaN  B11  NaN  NaN  C11  D11

In [ ]:
# since inner only gets the common columns, we only get the D column in our result
row_concat1 = pd.concat([df1, df2, df3], join = 'inner')
row_concat1

D
0   D0
1   D1
2   D2
3   D3
0   A4
1   A5
2   A6
3   A7
0   B8
1   B9
2  B10
3  B11

### Situations where Such Methods are Applicable

In [ ]:
# create a dataframe to be used next
addr1_df = pd.DataFrame({
    'Number' : ['114', '153/1', '102', '945'],
    'Building' : ['A', 'BeachFront', 'Main', 'C'],
    'Street' : ['Sai 1', 'Rama IX', 'Barom' , 'Yaek 9'],
    "City":["Salaya", "Payathai", "Salaya", "Aroonamarin"],
    "District":["Taweewattana", "Ratchtevee", "Taweewattana", "Bangkok Noi"],
    "Province":["Bangkok", "Bangkok", "Bangkok", "Bangkok"],
    "ZIP":[73710, 10400, 73710, 10700]})

addr1_df
                         

Number    Building   Street         City      District Province    ZIP
0    114           A    Sai 1       Salaya  Taweewattana  Bangkok  73710
1  153/1  BeachFront  Rama IX     Payathai    Ratchtevee  Bangkok  10400
2    102        Main    Barom       Salaya  Taweewattana  Bangkok  73710
3    945           C   Yaek 9  Aroonamarin   Bangkok Noi  Bangkok  10700

In [ ]:
# Create a dataframe to be used next
addr2_df = pd.DataFrame({
    "Number":["208", "2491", "327", "123"],
    "Street":["Rama VI", "Rama I", "Sukhumvit", "Charansanitwong"],
    "City":["SamSen Nai", "Bangrug", "Prakanong", "Bangplud"],
    "District":["Phayathai", "Ratchtevee", "Taweewattana", "Bangkok Noi"],
    "Province":["Bangkok", "Bangkok", "Bangkok", "Bangkok"],
    "Country":["Thailand", "Thailand", "Thailand", "Thailand"],
    "ZIP":[10100, 10400, 10600, 10200]
})
addr2_df

Number           Street        City      District Province   Country    ZIP
0    208          Rama VI  SamSen Nai     Phayathai  Bangkok  Thailand  10100
1   2491           Rama I     Bangrug    Ratchtevee  Bangkok  Thailand  10400
2    327        Sukhumvit   Prakanong  Taweewattana  Bangkok  Thailand  10600
3    123  Charansanitwong    Bangplud   Bangkok Noi  Bangkok  Thailand  10200

In [ ]:
# we get some NaN values - not what we want
addr_df = pd.concat([addr1_df, addr2_df])
addr_df

Number    Building           Street         City      District Province  \
0    114           A            Sai 1       Salaya  Taweewattana  Bangkok   
1  153/1  BeachFront          Rama IX     Payathai    Ratchtevee  Bangkok   
2    102        Main            Barom       Salaya  Taweewattana  Bangkok   
3    945           C           Yaek 9  Aroonamarin   Bangkok Noi  Bangkok   
0    208         NaN          Rama VI   SamSen Nai     Phayathai  Bangkok   
1   2491         NaN           Rama I      Bangrug    Ratchtevee  Bangkok   
2    327         NaN        Sukhumvit    Prakanong  Taweewattana  Bangkok   
3    123         NaN  Charansanitwong     Bangplud   Bangkok Noi  Bangkok   

     ZIP   Country  
0  73710       NaN  
1  10400       NaN  
2  73710       NaN  
3  10700       NaN  
0  10100  Thailand  
1  10400  Thailand  
2  10600  Thailand  
3  10200  Thailand

In [ ]:
# more concise than the outer join above
addr_df = pd.concat([addr1_df, addr2_df], join = 'inner')
addr_df

Number           Street         City      District Province    ZIP
0    114            Sai 1       Salaya  Taweewattana  Bangkok  73710
1  153/1          Rama IX     Payathai    Ratchtevee  Bangkok  10400
2    102            Barom       Salaya  Taweewattana  Bangkok  73710
3    945           Yaek 9  Aroonamarin   Bangkok Noi  Bangkok  10700
0    208          Rama VI   SamSen Nai     Phayathai  Bangkok  10100
1   2491           Rama I      Bangrug    Ratchtevee  Bangkok  10400
2    327        Sukhumvit    Prakanong  Taweewattana  Bangkok  10600
3    123  Charansanitwong     Bangplud   Bangkok Noi  Bangkok  10200

### Concatenate Columns with different rows

In [ ]:
# change the row labels
df1.index = [0,1,2,3]
df2.index = [2,3,4,5]
df3.index = [2,3,6,7]

In [ ]:
col_concat = pd.concat([df1, df2, df3], axis =1)
col_concat

A    B    C    D    D    E    F    G    A    D    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   A4   B4   C4   D4   A8   B8   C8   D8
3   A3   B3   C3   D3   A5   B5   C5   D5   A9   B9   C9   D9
4  NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
7  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [ ]:
# if we only want the rows that appear in all dataframes
pd.concat([df1, df2, df3], join = 'inner', axis =1)

A   B   C   D   D   E   F   G   A   D   G   H
2  A2  B2  C2  D2  A4  B4  C4  D4  A8  B8  C8  D8
3  A3  B3  C3  D3  A5  B5  C5  D5  A9  B9  C9  D9

In [ ]:
pd.concat([df1, df2, df3], axis = 0) # based on row-wise concatenation, default 

A    B    C    D    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN   A4   B4   C4   D4  NaN
3  NaN  NaN  NaN   A5   B5   C5   D5  NaN
4  NaN  NaN  NaN   A6   B6   C6   D6  NaN
5  NaN  NaN  NaN   A7   B7   C7   D7  NaN
2   A8  NaN  NaN   B8  NaN  NaN   C8   D8
3   A9  NaN  NaN   B9  NaN  NaN   C9   D9
6  A10  NaN  NaN  B10  NaN  NaN  C10  D10
7  A11  NaN  NaN  B11  NaN  NaN  C11  D11

In [ ]:
pd.concat([df1, df2, df3], axis = 1) # based on column-wise concatenation

A    B    C    D    D    E    F    G    A    D    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   A4   B4   C4   D4   A8   B8   C8   D8
3   A3   B3   C3   D3   A5   B5   C5   D5   A9   B9   C9   D9
4  NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
7  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

# Merging

In [ ]:
# download our other files for the next tasks

person = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_person.csv")
site = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_site.csv")
survey = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_survey.csv")
visited = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_visited.csv")

In [ ]:
person

ident   personal    family
0      dyer    William      Dyer
1        pb      Frank   Pabodie
2      lake   Anderson      Lake
3       roe  Valentina   Roerich
4  danforth      Frank  Danforth

In [ ]:
site

name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40

In [ ]:
survey

taken person quant  reading
0     619   dyer   rad     9.82
1     619   dyer   sal     0.13
2     622   dyer   rad     7.80
3     622   dyer   sal     0.09
4     734     pb   rad     8.41
5     734   lake   sal     0.05
6     734     pb  temp   -21.50
7     735     pb   rad     7.22
8     735    NaN   sal     0.06
9     735    NaN  temp   -26.00
10    751     pb   rad     4.35
11    751     pb  temp   -18.50
12    751   lake   sal     0.10
13    752   lake   rad     2.19
14    752   lake   sal     0.09
15    752   lake  temp   -16.00
16    752    roe   sal    41.60
17    837   lake   rad     1.46
18    837   lake   sal     0.21
19    837    roe   sal    22.50
20    844    roe   rad    11.25

In [ ]:
visited

ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

In [ ]:
site

name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40

In [ ]:
# One to one merge
visited_subset = visited.loc[[0, 2, 6]]
visited_subset

ident   site       dated
0    619   DR-1  1927-02-08
2    734   DR-3  1939-01-07
6    837  MSK-4  1932-01-14

In [ ]:
# both the dataframes above have similar content but the content is under different names
# we can merge based on that

# if just do this, merge wont work since we dont have any common column to perform on
one2one_merge = site.merge(visited_subset)
one2one_merge

# Merge error

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [ ]:
one2one_merge = site.merge(visited_subset, left_on = 'name', right_on = 'site')
one2one_merge

In [ ]:
# we can switch as well
one2one_merge = visited_subset.merge(site, left_on = 'site', right_on = 'name')
one2one_merge

In [ ]:
# however, we can use join to get a similar result 
# but with Nan values since site does not have index 6
one2one_join = visited_subset.join(site)
one2one_join

ident   site       dated   name    lat    long
0    619   DR-1  1927-02-08   DR-1 -49.85 -128.57
2    734   DR-3  1939-01-07  MSK-4 -48.87 -123.40
6    837  MSK-4  1932-01-14    NaN    NaN     NaN

In [ ]:
# since visited_subset only covers [[0,2,6]] -> row 1 shows nan values for visited_subset
one2one_join = site.join(visited_subset) 
one2one_join

name    lat    long  ident  site       dated
0   DR-1 -49.85 -128.57  619.0  DR-1  1927-02-08
1   DR-3 -47.15 -126.72    NaN   NaN         NaN
2  MSK-4 -48.87 -123.40  734.0  DR-3  1939-01-07

In [ ]:
# same data but in site df, its called "name"
# in visited df, its called "site"
Many2One_merge = visited.merge(site, left_on = 'site', right_on = 'name')
Many2One_merge                         

ident   site       dated   name    lat    long
0    619   DR-1  1927-02-08   DR-1 -49.85 -128.57
1    622   DR-1  1927-02-10   DR-1 -49.85 -128.57
2    734   DR-3  1939-01-07   DR-3 -47.15 -126.72
3    735   DR-3  1930-01-12   DR-3 -47.15 -126.72
4    751   DR-3  1930-02-26   DR-3 -47.15 -126.72
5    752   DR-3         NaN   DR-3 -47.15 -126.72
6    837  MSK-4  1932-01-14  MSK-4 -48.87 -123.40
7    844   DR-1  1932-03-22   DR-1 -49.85 -128.57

In [ ]:
# Same concept as given above, we just swap the order
One2Many_merge = site.merge(visited, left_on = 'name', right_on = 'site')
One2Many_merge                

name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-1 -49.85 -128.57    622   DR-1  1927-02-10
2   DR-1 -49.85 -128.57    844   DR-1  1932-03-22
3   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
4   DR-3 -47.15 -126.72    735   DR-3  1930-01-12
5   DR-3 -47.15 -126.72    751   DR-3  1930-02-26
6   DR-3 -47.15 -126.72    752   DR-3         NaN
7  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

In [ ]:
# Manyto Many Merge
enrollment_df = pd.DataFrame({
    'ID' : [1001, 1002],
    'Course' : ["ICCS161", "ICCS161"]
})
enrollment_df

ID   Course
0  1001  ICCS161
1  1002  ICCS161

In [ ]:
exam_df = pd.DataFrame({
    "Course": ["ICCS161", "ICCS161"],
    "Exam": ["Midterm", "Final"]
})
exam_df

Course     Exam
0  ICCS161  Midterm
1  ICCS161    Final

In [ ]:
Many2Many_merge = enrollment_df.merge(exam_df, left_on = 'Course', right_on = 'Course')
Many2Many_merge                                     

ID   Course     Exam
0  1001  ICCS161  Midterm
1  1001  ICCS161    Final
2  1002  ICCS161  Midterm
3  1002  ICCS161    Final

In [ ]:
enrollment_df_2 = pd.DataFrame({
    "ID": [1001, 1002, 1003],
    "Course": ["ICCS161", "ICCS161", "ICCS331"]
})
enrollment_df_2

ID   Course
0  1001  ICCS161
1  1002  ICCS161
2  1003  ICCS331

In [ ]:
# since ICCS331 is not a match in exam_df, it doesnt show up at all
Many2Many_merge_2 = enrollment_df_2.merge(exam_df, left_on = 'Course', right_on = 'Course')
Many2Many_merge_2

ID   Course     Exam
0  1001  ICCS161  Midterm
1  1001  ICCS161    Final
2  1002  ICCS161  Midterm
3  1002  ICCS161    Final

In [ ]:
# change the name of the index and merge on that basis
enrollment_df_2.set_index('Course', inplace = True)
enrollment_df_2

ID
Course       
ICCS161  1001
ICCS161  1002
ICCS331  1003

In [ ]:
exam_df.set_index('Course', inplace = True)
exam_df

Exam
Course          
ICCS161  Midterm
ICCS161    Final

In [ ]:
# since we are using "outer" , even 1003 shows up but just with a Nan value
joiney = enrollment_df_2.join(exam_df, how = 'outer')
joiney                     

ID     Exam
Course                
ICCS161  1001  Midterm
ICCS161  1001    Final
ICCS161  1002  Midterm
ICCS161  1002    Final
ICCS331  1003      NaN

In [ ]:
# with inner, only the common values show up
joiney2 = enrollment_df_2.join(exam_df, how = 'inner')
joiney2   

ID     Exam
Course                
ICCS161  1001  Midterm
ICCS161  1001    Final
ICCS161  1002  Midterm
ICCS161  1002    Final

### Conclusion - Similarities and Differences between Concat, Merge, and Join

In [ ]:
df1 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_1.csv")
df2 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_2.csv")

In [ ]:
df3 = df2.copy()

df3.iloc[2] = df1.iloc[1]
df3.iloc[3] = df1.iloc[2]

df2.columns = ['D', 'E', 'F', 'G']
df3.columns = ['A', 'D', 'G', 'H']

df2.index=[0, 2, 3, 5]
df3.index=[2, 3, 6, 7]

In [ ]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

D   E   F   G
0  A4  B4  C4  D4
2  A5  B5  C5  D5
3  A6  B6  C6  D6
5  A7  B7  C7  D7

In [ ]:
df3

A   D   G   H
2  A4  B4  C4  D4
3  A5  B5  C5  D5
6  A1  B1  C1  D1
7  A2  B2  C2  D2

In [ ]:
pd.concat([df1, df2])


A    B    C   D    E    F    G
0   A0   B0   C0  D0  NaN  NaN  NaN
1   A1   B1   C1  D1  NaN  NaN  NaN
2   A2   B2   C2  D2  NaN  NaN  NaN
3   A3   B3   C3  D3  NaN  NaN  NaN
0  NaN  NaN  NaN  A4   B4   C4   D4
2  NaN  NaN  NaN  A5   B5   C5   D5
3  NaN  NaN  NaN  A6   B6   C6   D6
5  NaN  NaN  NaN  A7   B7   C7   D7

In [ ]:
pd.concat([df1, df2], axis =1)

A    B    C    D    D    E    F    G
0   A0   B0   C0   D0   A4   B4   C4   D4
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   A5   B5   C5   D5
3   A3   B3   C3   D3   A6   B6   C6   D6
5  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [ ]:
pd.concat([df1, df2], join = 'inner')

D
0  D0
1  D1
2  D2
3  D3
0  A4
2  A5
3  A6
5  A7

In [ ]:
pd.concat([df1, df2], axis = 1, join = 'inner')

A   B   C   D   D   E   F   G
0  A0  B0  C0  D0  A4  B4  C4  D4
2  A2  B2  C2  D2  A5  B5  C5  D5
3  A3  B3  C3  D3  A6  B6  C6  D6

In [ ]:
df1.join(df2, lsuffix="_left", rsuffix="_right", how ='outer')

A    B    C D_left D_right    E    F    G
0   A0   B0   C0     D0      A4   B4   C4   D4
1   A1   B1   C1     D1     NaN  NaN  NaN  NaN
2   A2   B2   C2     D2      A5   B5   C5   D5
3   A3   B3   C3     D3      A6   B6   C6   D6
5  NaN  NaN  NaN    NaN      A7   B7   C7   D7

In [ ]:
pd.merge(df1, df2, left_index=True, right_index=True)

A   B   C D_x D_y   E   F   G
0  A0  B0  C0  D0  A4  B4  C4  D4
2  A2  B2  C2  D2  A5  B5  C5  D5
3  A3  B3  C3  D3  A6  B6  C6  D6

In [ ]:
# based on left - df1 indexes only
df1.join(df2, lsuffix="_left", rsuffix="_right", how='left')

A   B   C D_left D_right    E    F    G
0  A0  B0  C0     D0      A4   B4   C4   D4
1  A1  B1  C1     D1     NaN  NaN  NaN  NaN
2  A2  B2  C2     D2      A5   B5   C5   D5
3  A3  B3  C3     D3      A6   B6   C6   D6

In [ ]:
# based on right - df2 indexes only
df1.join(df2, lsuffix="_left", rsuffix="_right", how ='right')

A    B    C D_left D_right   E   F   G
0   A0   B0   C0     D0      A4  B4  C4  D4
2   A2   B2   C2     D2      A5  B5  C5  D5
3   A3   B3   C3     D3      A6  B6  C6  D6
5  NaN  NaN  NaN    NaN      A7  B7  C7  D7

In [ ]:
pd.merge(df1, df2, left_index=True, right_index=True, how='left')

A   B   C D_x  D_y    E    F    G
0  A0  B0  C0  D0   A4   B4   C4   D4
1  A1  B1  C1  D1  NaN  NaN  NaN  NaN
2  A2  B2  C2  D2   A5   B5   C5   D5
3  A3  B3  C3  D3   A6   B6   C6   D6

In [ ]:
pd.merge(df1, df2, left_index=True, right_index=True, how='right')

A    B    C  D_x D_y   E   F   G
0   A0   B0   C0   D0  A4  B4  C4  D4
2   A2   B2   C2   D2  A5  B5  C5  D5
3   A3   B3   C3   D3  A6  B6  C6  D6
5  NaN  NaN  NaN  NaN  A7  B7  C7  D7