In [222]:
import numpy as np
import pandas as pd


In [129]:
x = np.array([[1,2], [3,4], [5,6]])
y = np.array([[7,8]])

m = np.array([1,2,3,4])
n = np.array([5,6,7,8])
            
             
ans = np.append(x, y) 
ans # array([1, 2, 3, 4, 5, 6, 7, 8])

res = np.append(m,n)



print("x: ", x)
print("y: ",y)
print("ans: ",ans)
print("m: ",m)
print("n: ",n)
print("res: ",res)

x:  [[1 2]
 [3 4]
 [5 6]]
y:  [[7 8]]
ans:  [1 2 3 4 5 6 7 8]
m:  [1 2 3 4]
n:  [5 6 7 8]
res:  [1 2 3 4 5 6 7 8]


In [130]:
a = np.zeros(3)
print(a)
b = np.identity(8)
print(b)


[0. 0. 0.]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [131]:
arr1 = np.random.rand(3,2)
arr1

array([[0.01711673, 0.26712136],
       [0.39563865, 0.78556463],
       [0.77020669, 0.30897896]])

In [132]:
arr2 = np.random.randint(0, 20, 5)
arr2

array([15, 16, 11, 19, 11])

In [133]:
# Important Note:

[1,2,3,4] * [1,2,3,4] # TypeError


TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
[1,2,3,4] * 2

In [ ]:
np.array([1,2,3,4]) * 2

In [ ]:
# praticing creating a series 

people = ["A", "B", "C", "D"]
age = [12, 13, 16, 15]
arr = np.array(age)
dct = {"A" : 12, "B" : 13, "C" : 16, "D" : 15}


In [ ]:
# We can create a Series from a list, an array and a dictionary 
s1 = pd.Series(age, people)
s2 = pd.Series(dct)
s3 = pd.Series(arr, people)


In [ ]:
s6 = pd.Series([22,33,44], ["A", "B", "C"])
s7 = pd.Series([22,33,44], [2,3,4])
s6[0] # np.int64(22)
# s7[0] # since in s7, our index in numerical, [0] shows us KeyError
s7[3] # gets 33


In [ ]:
s7.iloc[0] # to acces the index, use iloc instead

In [ ]:
s8 = pd.Series([22, 25, 27], ['H', 'A', 'Y'])

# changing a value
s8['H'] = 23

# appending a value
s8['S'] = 29

s8

In [ ]:
# dropping a value

s8.drop(['S']) # wont work like this

# either you reassign it to some otehr value or you inplace = True

s8.drop(['S'], inplace = True)
# or
s9 = s8.drop(['S'])
s9

In [ ]:
df = pd.DataFrame({
    "Name" : ["A", "B", "C"],
    "Age" : [ 15, 13, 19],
    "Place" : ['Bangkok', 'Tokyo', 'Singapore']},
    ["Winner", "Runner1", "Runner2"])

df
                  

In [ ]:
A = pd.Series(['A', 'B', 'C'])
B = pd.Series([16, 18, 19])

x = pd.DataFrame()
x['Name'] = A
x['Age'] = B

index = pd.Series(['Man', 'Woman', 'Trans'])

x.set_index(index, inplace = True)
print(x)
# do inplace = True if you wanna make it true for x as well and not just the variable ans



In [ ]:
df1 = pd.DataFrame({
    "City" : ["Bangkok", "Washington", "Delhi"],
    "Religion" : ['Buddhism', 'Athiest' , 'Hinduism'],
    'Continent' : ['Asia', 'North America', 'Asia']
},
                   ['Best', 'Medium', 'Worst'])

df1
                   

In [ ]:
df1.loc['Best'] # think of loc as the lock of the dataframe ie index, you gotta put the name of the index

In [ ]:
df1.iloc[0] # via index numbers

In [ ]:
df1.iloc[[0]]

In [ ]:
x = df1.iloc[1]
x

In [ ]:
x.iloc[1]

In [ ]:
df1.iloc[1,2] = 'N. America'
df1

In [ ]:
df1.loc['Medium', 'Continent'] = 'North America'
df1

In [ ]:
df2 = pd.DataFrame({
    'City' : ['Cairo'],
    'Religion' : ['Muslim'],
    'Continent' : ['Africa']},
                   ['Meh'])
    

df2

In [134]:
addi = pd.concat([df1, df2])
addi

ID            Name  Major  GPA
0  6780001      Ann Molive   ICCH  3.2
1  6780002      Ben Kenobi   ICJD  NaN
2  6780003   Peter Cruiser   ICBA  3.3
3  6780004      Bob Hanger   ICFS  3.5
4  6780005        Moe Otto   ICCS  3.1
0  6780031         Tom Lee   ICCS  2.7
1  6780032        Pat Cade   ICFS  3.8
2  6780033      Will Power   ICBA  2.7
3  6780034      Arty Didas   ICFS  3.2
4  6780035       Bart Yolo   ICCS  1.7

In [135]:
df1 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/muic1.csv")
df2 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/muic2.csv")
df3 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/muic3.csv")

In [136]:
df = pd.concat([df1,df2,df3], )
df

ID               Name  Major  GPA
0  6780001         Ann Molive   ICCH  3.2
1  6780002         Ben Kenobi   ICJD  NaN
2  6780003      Peter Cruiser   ICBA  3.3
3  6780004         Bob Hanger   ICFS  3.5
4  6780005           Moe Otto   ICCS  3.1
0  6780031            Tom Lee   ICCS  2.7
1  6780032           Pat Cade   ICFS  3.8
2  6780033         Will Power   ICBA  2.7
3  6780034         Arty Didas   ICFS  3.2
4  6780035          Bart Yolo   ICCS  1.7
0  6780021         Terry Cuda   ICCS  1.9
1  6780022        Justin Bull   ICBA  2.8
2  6780023       Ed Cheerbeer   ICCS  4.0
3  6780024          Luke Warm   ICCS  1.2
4  6780025   Anakin Skywalker   ICJD  NaN

In [137]:
df.loc[3]

ID         Name  Major  GPA
3  6780004   Bob Hanger   ICFS  3.5
3  6780034   Arty Didas   ICFS  3.2
3  6780024    Luke Warm   ICCS  1.2

In [138]:
df.iloc[[3]]

ID         Name  Major  GPA
3  6780004   Bob Hanger   ICFS  3.5

In [139]:
df = pd.concat([df1, df2, df3], ignore_index = True)
df

ID               Name  Major  GPA
0   6780001         Ann Molive   ICCH  3.2
1   6780002         Ben Kenobi   ICJD  NaN
2   6780003      Peter Cruiser   ICBA  3.3
3   6780004         Bob Hanger   ICFS  3.5
4   6780005           Moe Otto   ICCS  3.1
5   6780031            Tom Lee   ICCS  2.7
6   6780032           Pat Cade   ICFS  3.8
7   6780033         Will Power   ICBA  2.7
8   6780034         Arty Didas   ICFS  3.2
9   6780035          Bart Yolo   ICCS  1.7
10  6780021         Terry Cuda   ICCS  1.9
11  6780022        Justin Bull   ICBA  2.8
12  6780023       Ed Cheerbeer   ICCS  4.0
13  6780024          Luke Warm   ICCS  1.2
14  6780025   Anakin Skywalker   ICJD  NaN

In [141]:
person = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_person.csv")
site = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_site.csv")
survey = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_survey.csv")
visited = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_visited.csv"

In [143]:
person

ident   personal    family
0      dyer    William      Dyer
1        pb      Frank   Pabodie
2      lake   Anderson      Lake
3       roe  Valentina   Roerich
4  danforth      Frank  Danforth

In [144]:
site

name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40

In [145]:
survey

taken person quant  reading
0     619   dyer   rad     9.82
1     619   dyer   sal     0.13
2     622   dyer   rad     7.80
3     622   dyer   sal     0.09
4     734     pb   rad     8.41
5     734   lake   sal     0.05
6     734     pb  temp   -21.50
7     735     pb   rad     7.22
8     735    NaN   sal     0.06
9     735    NaN  temp   -26.00
10    751     pb   rad     4.35
11    751     pb  temp   -18.50
12    751   lake   sal     0.10
13    752   lake   rad     2.19
14    752   lake   sal     0.09
15    752   lake  temp   -16.00
16    752    roe   sal    41.60
17    837   lake   rad     1.46
18    837   lake   sal     0.21
19    837    roe   sal    22.50
20    844    roe   rad    11.25

In [146]:
visited

ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

In [147]:
# one to one merge
visited_sub = visited.loc[[0,2,6]]
visited_sub

ident   site       dated
0    619   DR-1  1927-02-08
2    734   DR-3  1939-01-07
6    837  MSK-4  1932-01-14

In [149]:
# no common columns to merge on, shows error: 

# so we merge based on the
x = site.merge(visited_sub, left_on = 'name', right_on = 'site')
x

name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
2  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

In [151]:

one2one_join = visited_sub.join(site)
one2one_join

ident   site       dated   name    lat    long
0    619   DR-1  1927-02-08   DR-1 -49.85 -128.57
2    734   DR-3  1939-01-07  MSK-4 -48.87 -123.40
6    837  MSK-4  1932-01-14    NaN    NaN     NaN

In [152]:
# merge
# merge performs on column names, only merges if the column names are same, otherwise, you need to specify the left and right
# data thats not common doesnt show up at all

# join
# ou gotta define "how = outer" to get all info, for only common info how = "inner"

# for concat, 
# use join = 'inner or outer

# for join and merge,
# you use how = 

In [153]:
df1 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_1.csv")
df2 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_2.csv")

df3 = df2.copy()

df3.iloc[2] = df1.iloc[1]
df3.iloc[3] = df1.iloc[2]

df2.columns = ['D', 'E', 'F', 'G']
df3.columns = ['A', 'D', 'G', 'H']

df2.index=[0, 2, 3, 5]
df3.index=[2, 3, 6, 7]

In [154]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [155]:
df2

D   E   F   G
0  A4  B4  C4  D4
2  A5  B5  C5  D5
3  A6  B6  C6  D6
5  A7  B7  C7  D7

In [156]:
df3

A   D   G   H
2  A4  B4  C4  D4
3  A5  B5  C5  D5
6  A1  B1  C1  D1
7  A2  B2  C2  D2

In [165]:
# for join we use lsuffix and rsuffix and it cannot join for two dataframes where the column name is same

df1.join(df2, lsuffix = '_l', rsuffix = '_r' ,how = 'outer')

A    B    C  D_l  D_r    E    F    G
0   A0   B0   C0   D0   A4   B4   C4   D4
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   A5   B5   C5   D5
3   A3   B3   C3   D3   A6   B6   C6   D6
5  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [181]:
df1.merge(df2, left_index = True, right_index = True, how= 'inner')

A   B   C D_x D_y   E   F   G
0  A0  B0  C0  D0  A4  B4  C4  D4
2  A2  B2  C2  D2  A5  B5  C5  D5
3  A3  B3  C3  D3  A6  B6  C6  D6

In [185]:
pd.concat([df1, df2])

A    B    C   D    E    F    G
0   A0   B0   C0  D0  NaN  NaN  NaN
1   A1   B1   C1  D1  NaN  NaN  NaN
2   A2   B2   C2  D2  NaN  NaN  NaN
3   A3   B3   C3  D3  NaN  NaN  NaN
0  NaN  NaN  NaN  A4   B4   C4   D4
2  NaN  NaN  NaN  A5   B5   C5   D5
3  NaN  NaN  NaN  A6   B6   C6   D6
5  NaN  NaN  NaN  A7   B7   C7   D7

In [186]:
pd.concat([df1, df2], join = 'inner' )

D
0  D0
1  D1
2  D2
3  D3
0  A4
2  A5
3  A6
5  A7

In [188]:
# Note: since we are using a data file on the web, we don't need to download it
df_rel = pd.read_csv('https://raw.githubusercontent.com/chendaniely/pydatadc_2018-tidy/master/data/pew.csv')

df_rel.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   religion            18 non-null     object
 1   <$10k               18 non-null     int64 
 2   $10-20k             18 non-null     int64 
 3   $20-30k             18 non-null     int64 
 4   $30-40k             18 non-null     int64 
 5   $40-50k             18 non-null     int64 
 6   $50-75k             18 non-null     int64 
 7   $75-100k            18 non-null     int64 
 8   $100-150k           18 non-null     int64 
 9   >150k               18 non-null     int64 
 10  Don't know/refused  18 non-null     int64 
dtypes: int64(10), object(1)
memory usage: 1.7+ KB


In [189]:
test = pd.melt(df_rel,
               id_vars = 'religion',
               var_name = 'income',
               value_vars = ['$40-50k', '$50-75k'],
               value_name = 'frequency')

test
               
               

religion   income  frequency
0                  Agnostic  $40-50k         76
1                   Atheist  $40-50k         35
2                  Buddhist  $40-50k         33
3                  Catholic  $40-50k        638
4        Don’t know/refused  $40-50k         10
5          Evangelical Prot  $40-50k        881
6                     Hindu  $40-50k         11
7   Historically Black Prot  $40-50k        197
8         Jehovah's Witness  $40-50k         21
9                    Jewish  $40-50k         30
10            Mainline Prot  $40-50k        651
11                   Mormon  $40-50k         56
12                   Muslim  $40-50k          9
13                 Orthodox  $40-50k         32
14          Other Christian  $40-50k         13
15             Other Faiths  $40-50k         49
16    Other World Religions  $40-50k          2
17             Unaffiliated  $40-50k        341
18                 Agnostic  $50-75k        137
19                  Atheist  $50-75k         70
20                 Buddhist  $50-75k         58
21                 Catholic  $50-75k       1116
22       Don’t know/refused  $50-75k         35
23         Evangelical Prot  $50-75k       1486
24                    Hindu  $50-75k         34
25  Historically Black Prot  $50-75k        223
26        Jehovah's Witness  $50-75k         30
27                   Jewish  $50-75k         95
28            Mainline Prot  $50-75k       1107
29                   Mormon  $50-75k        112
30                   Muslim  $50-75k         23
31                 Orthodox  $50-75k         47
32          Other Christian  $50-75k         14
33             Other Faiths  $50-75k         63
34    Other World Religions  $50-75k          7
35             Unaffiliated  $50-75k        528

In [193]:
# let's clean this dataset together
df_tb = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/tb.csv")
df_tb

country  year   m014  m1524   m2534  m3544  m4554  m5564    m65  mu   f014
0      AD  2000    0.0    0.0     1.0    0.0      0      0    0.0 NaN    NaN
1      AE  2000    2.0    4.0     4.0    6.0      5     12   10.0 NaN    3.0
2      AF  2000   52.0  228.0   183.0  149.0    129     94   80.0 NaN   93.0
3      AG  2000    0.0    0.0     0.0    0.0      0      0    1.0 NaN    1.0
4      AL  2000    2.0   19.0    21.0   14.0     24     19   16.0 NaN    3.0
5      AM  2000    2.0  152.0   130.0  131.0     63     26   21.0 NaN    1.0
6      AN  2000    0.0    0.0     1.0    2.0      0      0    0.0 NaN    0.0
7      AO  2000  186.0  999.0  1003.0  912.0    482    312  194.0 NaN  247.0
8      AR  2000   97.0  278.0   594.0  402.0    419    368  330.0 NaN  121.0
9      AS  2000    NaN    NaN     NaN    NaN      1      1    NaN NaN    NaN

In [194]:
df_tb.drop('mu', inplace = True, axis = 1)
df_tb

country  year   m014  m1524   m2534  m3544  m4554  m5564    m65   f014
0      AD  2000    0.0    0.0     1.0    0.0      0      0    0.0    NaN
1      AE  2000    2.0    4.0     4.0    6.0      5     12   10.0    3.0
2      AF  2000   52.0  228.0   183.0  149.0    129     94   80.0   93.0
3      AG  2000    0.0    0.0     0.0    0.0      0      0    1.0    1.0
4      AL  2000    2.0   19.0    21.0   14.0     24     19   16.0    3.0
5      AM  2000    2.0  152.0   130.0  131.0     63     26   21.0    1.0
6      AN  2000    0.0    0.0     1.0    2.0      0      0    0.0    0.0
7      AO  2000  186.0  999.0  1003.0  912.0    482    312  194.0  247.0
8      AR  2000   97.0  278.0   594.0  402.0    419    368  330.0  121.0
9      AS  2000    NaN    NaN     NaN    NaN      1      1    NaN    NaN

In [196]:
df_tb_m = pd.melt(df_tb,
                  id_vars = ['country', 'year'],
                  var_name = 'sex_and_age',
                  value_name = 'cases')
df_tb_m
                            

country  year sex_and_age  cases
0       AD  2000        m014    0.0
1       AE  2000        m014    2.0
2       AF  2000        m014   52.0
3       AG  2000        m014    0.0
4       AL  2000        m014    2.0
..     ...   ...         ...    ...
75      AM  2000        f014    1.0
76      AN  2000        f014    0.0
77      AO  2000        f014  247.0
78      AR  2000        f014  121.0
79      AS  2000        f014    NaN

[80 rows x 4 columns]

In [216]:
df_tb_m['sex'] = df_tb_m['sex_and_age'].str[0:1]
df_tb_m['lower_bound_age'] = df_tb_m['sex_and_age'].str[1]
df_tb_m['upper_bound_age'] = df_tb_m['sex_and_age'].str[2:4]

df_tb_m['age'] = df_tb_m['lower_bound_age'] + '-' + df_tb_m['upper_bound_age']


KeyError: 'sex_and_age'

In [217]:
df_tb_m.drop(['sex_and_age', 'lower_bound_age','upper_bound_age'], axis=1, inplace = True)

KeyError: "['sex_and_age', 'lower_bound_age', 'upper_bound_age'] not found in axis"

In [221]:
df_tb_m = df_tb_m.astype({'cases': 'int'})
df_tb_m

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer: Error while type casting for column 'cases'

In [223]:
df_bill = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/billboard.csv")
df_bill

year      artist.inverted                                  track  time  \
0    2000      Destiny's Child               Independent Women Part I  3:38   
1    2000              Santana                           Maria, Maria  4:18   
2    2000        Savage Garden                     I Knew I Loved You  4:07   
3    2000              Madonna                                  Music  3:45   
4    2000  Aguilera, Christina  Come On Over Baby (All I Want Is You)  3:38   
..    ...                  ...                                    ...   ...   
312  2000     Ghostface Killah                       Cherchez LaGhost  3:04   
313  2000          Smith, Will                            Freakin' It  3:58   
314  2000        Zombie Nation                          Kernkraft 400  3:30   
315  2000       Eastsidaz, The                               Got Beef  3:58   
316  2000               Fragma                         Toca's Miracle  3:22   

    genre date.entered date.peaked  x1st.week  x2nd.week  x3rd.week  ...  \
0    Rock   2000-09-23  2000-11-18         78       63.0       49.0  ...   
1    Rock   2000-02-12  2000-04-08         15        8.0        6.0  ...   
2    Rock   1999-10-23  2000-01-29         71       48.0       43.0  ...   
3    Rock   2000-08-12  2000-09-16         41       23.0       18.0  ...   
4    Rock   2000-08-05  2000-10-14         57       47.0       45.0  ...   
..    ...          ...         ...        ...        ...        ...  ...   
312   R&B   2000-08-05  2000-08-05         98        NaN        NaN  ...   
313   Rap   2000-02-12  2000-02-12         99       99.0       99.0  ...   
314  Rock   2000-09-02  2000-09-02         99       99.0        NaN  ...   
315   Rap   2000-07-01  2000-07-01         99       99.0        NaN  ...   
316   R&B   2000-10-28  2000-10-28         99        NaN        NaN  ...   

     x67th.week  x68th.week  x69th.week  x70th.week  x71st.week  x72nd.week  \
0           NaN         NaN         NaN         NaN         NaN         NaN   
1           NaN         NaN         NaN         NaN         NaN         NaN   
2           NaN         NaN         NaN         NaN         NaN         NaN   
3           NaN         NaN         NaN         NaN         NaN         NaN   
4           NaN         NaN         NaN         NaN         NaN         NaN   
..          ...         ...         ...         ...         ...         ...   
312         NaN         NaN         NaN         NaN         NaN         NaN   
313         NaN         NaN         NaN         NaN         NaN         NaN   
314         NaN         NaN         NaN         NaN         NaN         NaN   
315         NaN         NaN         NaN         NaN         NaN         NaN   
316         NaN         NaN         NaN         NaN         NaN         NaN   

     x73rd.week  x74th.week  x75th.week  x76th.week  
0           NaN         NaN         NaN         NaN  
1           NaN         NaN         NaN         NaN  
2           NaN         NaN         NaN         NaN  
3           NaN         NaN         NaN         NaN  
4           NaN         NaN         NaN         NaN  
..          ...         ...         ...         ...  
312         NaN         NaN         NaN         NaN  
313         NaN         NaN         NaN         NaN  
314         NaN         NaN         NaN         NaN  
315         NaN         NaN         NaN         NaN  
316         NaN         NaN         NaN         NaN  

[317 rows x 83 columns]

In [224]:
test = pd.melt(df_bill,
               id_vars = ['year', 'artist.inverted', 'track', 'genre'],
               value_vars = ['x1st.week', 'x2nd.week', 'x3rd.week'],
               value_name = 'Frequency',
               var_name = 'Timelines')
test

year      artist.inverted                                  track genre  \
0    2000      Destiny's Child               Independent Women Part I  Rock   
1    2000              Santana                           Maria, Maria  Rock   
2    2000        Savage Garden                     I Knew I Loved You  Rock   
3    2000              Madonna                                  Music  Rock   
4    2000  Aguilera, Christina  Come On Over Baby (All I Want Is You)  Rock   
..    ...                  ...                                    ...   ...   
946  2000     Ghostface Killah                       Cherchez LaGhost   R&B   
947  2000          Smith, Will                            Freakin' It   Rap   
948  2000        Zombie Nation                          Kernkraft 400  Rock   
949  2000       Eastsidaz, The                               Got Beef   Rap   
950  2000               Fragma                         Toca's Miracle   R&B   

     Timelines  Frequency  
0    x1st.week       78.0  
1    x1st.week       15.0  
2    x1st.week       71.0  
3    x1st.week       41.0  
4    x1st.week       57.0  
..         ...        ...  
946  x3rd.week        NaN  
947  x3rd.week       99.0  
948  x3rd.week        NaN  
949  x3rd.week        NaN  
950  x3rd.week        NaN  

[951 rows x 6 columns]

In [226]:
test.dropna()
test

year      artist.inverted                                  track genre  \
0    2000      Destiny's Child               Independent Women Part I  Rock   
1    2000              Santana                           Maria, Maria  Rock   
2    2000        Savage Garden                     I Knew I Loved You  Rock   
3    2000              Madonna                                  Music  Rock   
4    2000  Aguilera, Christina  Come On Over Baby (All I Want Is You)  Rock   
..    ...                  ...                                    ...   ...   
946  2000     Ghostface Killah                       Cherchez LaGhost   R&B   
947  2000          Smith, Will                            Freakin' It   Rap   
948  2000        Zombie Nation                          Kernkraft 400  Rock   
949  2000       Eastsidaz, The                               Got Beef   Rap   
950  2000               Fragma                         Toca's Miracle   R&B   

     Timelines  Frequency  
0    x1st.week       78.0  
1    x1st.week       15.0  
2    x1st.week       71.0  
3    x1st.week       41.0  
4    x1st.week       57.0  
..         ...        ...  
946  x3rd.week        NaN  
947  x3rd.week       99.0  
948  x3rd.week        NaN  
949  x3rd.week        NaN  
950  x3rd.week        NaN  

[951 rows x 6 columns]