In [82]:
import numpy as np 
import pandas as pd

## 1-D Array

In [83]:
my_list = [11, 13, 15]
my_list                  # [11, 13, 15]
np.array([11, 13, 15])   # array([11, 13, 15])

array([11, 13, 15])

In [85]:
x = np.array([11, 13, 15, 16])
x.shape            

(4,)

In [87]:
x[1]
type(x) # numpy.ndarray
type(my_list) # list

np.int64(13)

In [5]:
print(type(x.shape)) # this will be a tuple
print(len(x.shape)) # this will show length of the tuple

<class 'tuple'>
1


In [6]:
a = (3, 4)
print(type(a)) # tuple
print(len(a)) # 2

<class 'tuple'>
2


## 2-D Arrays

In [90]:
my_2d_list = [[1,2] , [3,4] , [5,6]] 
my_2d_list

[[1, 2], [3, 4], [5, 6]]

In [8]:
y = np.array(my_2d_list)
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
# We can access using index
y[2]   # [5, 6] 
y[0,0] # y[0][0]   same result: 1
y[2,1] # y[2][1]   same result: 6

np.int64(6)

In [95]:
# Create a 2-d array with data 

y = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]


z = [[10,20,30,40],
      [50, 60, 70, 80],
      [90, 100, 110, 120]] 


print(z[1][3]) # 80
print(y[0][1]) # 2
print(z[2][2]) # 110

80
2
110


In [97]:
# Create a 3-d array with data

n = [ [[1,2,3],
       [4,5,6]],
     
     [[23, 24, 25],
      [26, 27, 28]],

     [[66,65,64],
      [63,62,61]]
    ]
       

m = [
    
    [[1,2,3],
     [4,5,6]],
    
      [[10,20,30],
      [40,50,60]],
    
     [[100,200,300],
      [400,500,600]]
]

assert m[0][0][0] == 1
assert m[1][1][0] == 40
assert m[0][0][1] == 2
assert m[2][1][2] == 600
assert n[2][0][0] == 66
assert n[0][1][2] == 6

In [106]:
# Crud - create, read, update, delete  ---- we created lists above already 


# -------- read
# Accessing a row 
# my_2d_list = [ [1,2] , [3,4] , [5,6]] 

my_2d_list[:][2] # [5, 6]
my_2d_list[2][0] # 5
m[-2:-1][0] # [[10, 20, 30], [40, 50, 60]]
my_2d_list[:][0] # [1, 2]

[1, 2]

In [14]:
# -------- update

my_2d_list[2][1] = 444
my_2d_list

[[1, 2], [3, 4], [5, 444]]

In [15]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[7, 8]])
arr3 = np.append(arr1, arr2) # It returns a new array. It doesn't add arr2 to arr1.
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
print(arr3.shape) # Will get (8,)
arr4 = arr3.reshape(4, 2) # It doesn't change arr3, but use data to make a new array
print(arr3)
print('---')
print(arr4)

(8,)
[1 2 3 4 5 6 7 8]
---
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
# delete - we cannot delete existing items
# np.delete(array, index, axis)
# axis 0 is along rows, axis 1 is along the columns

arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

# we want to delete row [5,6], it is in row 2 axis 0

arr2 = np.delete(arr1, 2, 0)
arr2

array([[1, 2],
       [3, 4],
       [7, 8]])

In [18]:
# delete column 2 4 6 8
arr3 = np.delete(arr1, 1, 1)
arr3

array([[1],
       [3],
       [5],
       [7]])

In [19]:
print(arr1)
print('---')
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
---
[[1]
 [3]
 [5]
 [7]]


## Some Useful Functions

In [20]:
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr2 = np.arange(0, 10, 4)
arr2

array([0, 4, 8])

In [22]:
arr3 = np.zeros(3)
arr4 = np.zeros((3,4))
arr5 = np.ones((3,4))
arr6 = np.identity(3)
print(arr3)
print('---------------')
print(arr4)
print('---------------')
print(arr5)
print('---------------')
print(arr6)

[0. 0. 0.]
---------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
---------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
---------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
arr7 = np.eye(3)
arr8 = np.eye(5, k=1)

print(arr7)
print(arr8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [24]:
arr9 = np.random.rand(3, 2)
arr9

p = np.random.randint(0, 100, 30) # range of 0 to 100, 30 numbers in the array
p

array([55, 95,  5,  0, 90, 56, 33, 56, 61, 75, 73, 84, 16, 14, 82,  4, 68,
       88, 94, 66, 27, 60, 95, 96, 23, 12, 61, 78, 42, 95])

In [25]:
p.reshape(2,15)
p

array([55, 95,  5,  0, 90, 56, 33, 56, 61, 75, 73, 84, 16, 14, 82,  4, 68,
       88, 94, 66, 27, 60, 95, 96, 23, 12, 61, 78, 42, 95])

In [26]:
p.min() # 1
p.max() # 98
p.argmin() # indice of the minimum number 
p.argmax() # indice of the maximum number

np.int64(23)

## Operations with matrices

In [27]:
a = [1, 3, 5]
b = [20, 30 , 40]
a + b 

[1, 3, 5, 20, 30, 40]

In [28]:
d = np.array([1, 3, 5])
e = np.array([10, 100, 1000])
d + e

array([  11,  103, 1005])

In [29]:
# if the dimensions are not the same, we get an error message
d = np.array([1, 3, 5])
e = np.array([10, 100, 1000, 10000])
d + e

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
f = np.array(["ha", "ho"])
g = np.array(["hey", "how"])
h = np.append(f, g)
h

## multiply 

## Multiply with the matrix

In [ ]:
m = np.array([1,2,3])
m*2

In [ ]:
[2,4,6] * 3 #since its not written as an array anymore, the output changes

In [ ]:
i = np.array([1,2,3,4])
i*i

In [ ]:
[1,  4,  9, 16] * [1,  4,  9, 16] # type error 

In [ ]:
[1,  4,  9, 16] * 2

# Pandas

## 1. Pandas - Series


In [ ]:
name = ["Abby", "Dylan", "Hope"]
num = [12, 15, 13]
num_arr = np.array(num)
dct = {"Abby" : 12, "Dylan" : 15, "Hope" : 13}

In [ ]:
series1 = pd.Series(num)
series1

In [ ]:
series1 = pd.Series(num, index = name)
series1

In [ ]:
series1.shape

In [ ]:
# we can also create a series from a numpy array
series2 = pd.Series(num_arr, name) 
series2

In [ ]:
# we can create a series from a dictionary
series3 = pd.Series(dct)
series3

In [ ]:
lst = [2.45, 3.67, 4.97]
lst_s = pd.Series(lst)
print(lst_s)
print(lst_s[0]) # 2.45
print(lst_s[2]) # 4.97

In [ ]:
s5 = pd.Series([22, 33, 44], ['One', 'Two', 'Three']) # (data, index)
s5

In [ ]:
# another way to access the data is through the named index itself
print(s5['One'])
print(s5['Three'])

In [ ]:
s77 = pd.Series(data=[22, 25, 27] , index=[5, 7, 9])
print(s77)
print(s77[5])
print(s77[0]) # Key error since Pandas thinks that [0] is an index and we dont have that index name

In [ ]:
# to access a position without using the index name
print(s77.iloc[0]) # use iloc[] instead 
print(s77.iloc[1])

In [ ]:
s8 = pd.Series([22, 25, 27], ['H', 'A', 'Y'])
s8

In [ ]:
# changing the value 
s8['H'] = 23 
s8

In [ ]:
# appending a value
s8['S'] = 29
s8['E'] = 31
s8

In [ ]:
s9 = s8.drop(['S', 'E']) # s8.drop(labels = ['S', 'E'])
print(s8)
print('---------------')
print(s9)

In [ ]:
# Operations 

s1 = pd.Series([11,22,33])
s2 = pd.Series([11,22,33])
s1 + s2

In [ ]:
# Adds the value in accordance with the name of the index itself, 
# which is why we have no values for 'C' and 'D' since only one of the series contains the letters while both s3 and s4 have 'A' and 'B'
s3 = pd.Series([11,22,33], ['A', 'B', 'C'])
s4 = pd.Series([11,22,33], ['B', 'D', 'A'])
s3 + s4

## Pandas - DataFrame

In [ ]:
df = pd.DataFrame({
    'Gold' : [15, 20,15],
    'Silver' : [ 22, 66, 7],
    'Bronze' : [23, 2, 23],
    'Continent' : ['Europe', 'Asia', 'Asia']
     }, 
     [ 'France' , 'Thailand' , 'Vietnam'])

df
                  

In [ ]:
# we can create them separately as well 
my_dt = {
    'Gold' : [15, 20,15],
    'Silver' : [ 22, 66, 7],
    'Bronze' : [23, 2, 23],
    'Continent' : ['Europe', 'Asia', 'Asia']}

my_dt2 = ['France' , 'Thailand' , 'Vietnam']

df = pd.DataFrame(my_dt, my_dt2)
df

In [ ]:
# Create a dataframe by manually setting each column with a series.
df3 = pd.DataFrame()
ser1 = pd.Series([15, 20, 15])
ser2 = pd.Series([22, 66, 7])
ser3 = pd.Series([23, 2, 23])
ser4 = pd.Series(['Europe', 'Asia', 'Asia'])

df3['Gold'] = ser1
df3['Silver'] = ser2
df3['Bronze'] = ser3
df3['Continent'] = ser4

df3 

In [ ]:
# what about the index?

my_ind = pd.Series(['France', 'Thailand', 'Vietnam'])

df33 = df3.set_index(my_ind) 
print(df33)
print('----------------------')
print(df3)


In [ ]:
# still, if we call df3, it will show us the dataframe with no index naming. Hence, we use inplace = True to make permanent changes
df3.set_index(my_ind, inplace = True)
df3

In [ ]:
# Now, if we print both df3 and df33, we get the same result 
print(df33)
print('----------------------')
print(df3)

## Reading - subsetting columns, subsetting rows, acessing any particular element

In [ ]:
# accessing 
df['Continent'] # df['Continent'] -> pandas.core.series.Series

In [ ]:
# accessing 
df[['Continent']] # df['Continent'] -> pandas.core.series.Dataframe

In [ ]:
df[['Gold' , 'Continent']] 

In [ ]:
# subsetting rows
df.loc[0] # since our dataframe has countries as index and not [0,1,2], shows key error


In [ ]:
# which is why we use iloc instead 
df.iloc[0] # returns a series
df.iloc[[0]] # returns a dataframe

In [ ]:
df.iloc[1:3] #df.loc[1:3] wont work


In [ ]:
df.loc['Thailand'] # since now we used the name of our index, it works! - shows in series

In [ ]:
df.loc[['Thailand']] # - shows in dataframe
df.loc[['Thailand', 'France']]

In [ ]:
# Both rows and columns
df.iloc[2, 0:2] # 2nd row, first two columns but in series
df.iloc[[2], 0:2] # same but in datafram

In [ ]:
df.iloc[:,:] # all rows, all columns
df.iloc[:,1:-1] # all columns excceot the zeroth and the last
df.iloc[:2, [0,3]] # only the 0th and 3rd column
df.iloc[:2, :] # only the 0th and 1st row and all columns

In [ ]:
x = df.iloc[2]
x # type - series

In [ ]:
x.iloc[1, 2] # IndexError: too many indexes

In [ ]:
x.iloc[2] # type - numpy.int64

In [ ]:
x.iloc[[2]] # type - series 

In [ ]:
x.iloc[[2], [2]] # Indexing Error

In [ ]:
df.iloc[2,1] # 2nd row, 1st column number -->  7 (keep in mind: its a comma, not , 
df.iloc[2] # 2nd row but in series 

In [ ]:
# How to update values
# using iloc
df.iloc[2,2] = 17 # updates df[2nd row, 2nd column] to be 17
df

In [ ]:
# using iloc
df.loc['Thailand', 'Silver'] = 8
df # here, we used loc instead to access the index 

In [ ]:
# appending
dfplus = pd.DataFrame(
    {
        'Gold' : [5],
        'Silver' : [2],
        'Bronze' : [8],
        'Continent' : ['Europe']
    },
    ['England'])
dfplus

In [ ]:
df3 = pd.concat([df, dfplus])
df3

In [ ]:
df # stays the same

In [ ]:
df3['Abbreviation'] = pd.Series(['FR', 'TH' , 'CN', 'UK'], index = df3.index)
df3

In [ ]:
df3['Abbreviation'] = pd.Series(['FR', 'TH' , 'CN', 'UK'])
df3 # Nan values only

In [ ]:
# Delete rows
df3 = df3.drop("England")
df3

In [ ]:
# preserve a copy if you wanna make changes
df4 = df3.copy()
df4

In [ ]:
# axis 0 -> rows
# axis 1 -> columns

df4.drop("France", inplace = True)
df4

In [ ]:
df5 = df.copy()
df5

In [ ]:
df5 = df5.drop('Thailand', axis = 0)
# wont work on axis = 1 since 'Thailand'is a row name and not a column name 
df5 = df5.drop('Silver', axis= 1)
df5

In [ ]:
df # remains the same

In [ ]:
# for columns
df6 = df.copy()
df6.drop('Gold', axis = 1, inplace = True)
df6

In [ ]:
df7 = df.copy()
df7.drop("France", inplace=True)
df7

# Data Manipulation

In [ ]:
df1 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/muic1.csv")
df2 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/muic2.csv")
df3 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/muic3.csv")

In [ ]:
df1

In [ ]:
df2

In [ ]:
df3

In [ ]:
row_concat1 = pd.concat([df1, df2, df3])
row_concat1.shape

In [ ]:
row_concat1

In [ ]:
# we want to subset the 4th student out 
row_concat1.loc[3]
# but there are many rows in index 3 since they all match the label

In [ ]:
# to get the 4th row, we use iloc since iloc is the integer location
row_concat1.iloc[[3]] # [3] for dataframe

In [ ]:
# getting a better index
row_concat2 = pd.concat([df1, df2, df3], ignore_index = True)
row_concat2

### Adding a dataframe where columns are not identical


In [ ]:
# Case 1: A subset
narrower_df = pd.DataFrame({
    "ID" : [6781111, 6781112],
    "Name" : ["Jacky Chow", "Jet Loo"]
})
narrower_df

In [ ]:
# Major and GPA show NaN values 
dfx = pd.concat([df1, narrower_df])
dfx

In [ ]:
# Case 2: creating a dataframe with totally different columns
another_df = pd.DataFrame({
    "Hobby" : ["Reading", "Running"],
    "Club" : ["Board Game", "Debate"]
})
another_df

In [ ]:
dfy = pd.concat([df1, another_df])
dfy

In [ ]:
# case 3: some columns are the same
foo_df = pd.DataFrame({
    "ID" : [6780101, 6780102],
    "Major" : ["ICCH", "ICCS"],
    "Height" : [65, 59],
    "Weight" : [170, 180]})
foo_df

In [ ]:
dfz = pd.concat([df1, foo_df])
dfz

In [ ]:
# inner join - is structural - looks for columns that are in both the dataframes
dfz = pd.concat([df1, foo_df], join = "inner")
dfz

In [ ]:
# lets give our 0th index a nan value in major 
df1.loc[0, "Major"] = np.nan
df1

In [ ]:
# concat is based on structure and not values
dfz = pd.concat([df1, foo_df], join = "inner")
dfz

In [ ]:
# outer - default value of the concat function, 
# leaving it blank is the same as setting join = "outer"
dfz = pd.concat([df1, foo_df], join = "outer")
dfz

### Adding Columns

In [ ]:
# download our other files for the next tasks

df1 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_1.csv")
df2 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_2.csv")
df3 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_3.csv")

In [ ]:
df1

In [ ]:
df2

In [ ]:
df3

In [ ]:
row_concat = pd.concat([df1, df2, df3])
row_concat

In [ ]:
# if we want to add along the column, use axis = 1
col_concat = pd.concat([df1, df2, df3], axis = 1)
col_concat

In [ ]:
col_concat['A'] # gets all the A's columns

In [ ]:
# adding columns with different indexes
df1.columns = ['A', 'B', 'C', 'D']
df2.columns = ['D', 'E', 'F', 'G']
df3.columns = ['A', 'D', 'G', 'H']

In [ ]:
df1

In [ ]:
df2

In [ ]:
df3

In [ ]:
# all DataFrames have column D and hence, there is not a single NaN value there
row_concat = pd.concat([df1, df2, df3])
row_concat

In [ ]:
# since inner only gets the common columns, we only get the D column in our result
row_concat1 = pd.concat([df1, df2, df3], join = 'inner')
row_concat1

### Situations where Such Methods are Applicable

In [ ]:
# create a dataframe to be used next
addr1_df = pd.DataFrame({
    'Number' : ['114', '153/1', '102', '945'],
    'Building' : ['A', 'BeachFront', 'Main', 'C'],
    'Street' : ['Sai 1', 'Rama IX', 'Barom' , 'Yaek 9'],
    "City":["Salaya", "Payathai", "Salaya", "Aroonamarin"],
    "District":["Taweewattana", "Ratchtevee", "Taweewattana", "Bangkok Noi"],
    "Province":["Bangkok", "Bangkok", "Bangkok", "Bangkok"],
    "ZIP":[73710, 10400, 73710, 10700]})

addr1_df
                         

In [ ]:
# Create a dataframe to be used next
addr2_df = pd.DataFrame({
    "Number":["208", "2491", "327", "123"],
    "Street":["Rama VI", "Rama I", "Sukhumvit", "Charansanitwong"],
    "City":["SamSen Nai", "Bangrug", "Prakanong", "Bangplud"],
    "District":["Phayathai", "Ratchtevee", "Taweewattana", "Bangkok Noi"],
    "Province":["Bangkok", "Bangkok", "Bangkok", "Bangkok"],
    "Country":["Thailand", "Thailand", "Thailand", "Thailand"],
    "ZIP":[10100, 10400, 10600, 10200]
})
addr2_df

In [ ]:
# we get some NaN values - not what we want
addr_df = pd.concat([addr1_df, addr2_df])
addr_df

In [ ]:
# more concise than the outer join above
addr_df = pd.concat([addr1_df, addr2_df], join = 'inner')
addr_df

### Concatenate Columns with different rows

In [ ]:
# change the row labels
df1.index = [0,1,2,3]
df2.index = [2,3,4,5]
df3.index = [2,3,6,7]

In [ ]:
col_concat = pd.concat([df1, df2, df3], axis =1)
col_concat

In [ ]:
# if we only want the rows that appear in all dataframes
pd.concat([df1, df2, df3], join = 'inner', axis =1)

In [ ]:
pd.concat([df1, df2, df3], axis = 0) # based on row-wise concatenation, default 

In [ ]:
pd.concat([df1, df2, df3], axis = 1) # based on column-wise concatenation

# Merging

In [ ]:
# download our other files for the next tasks

person = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_person.csv")
site = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_site.csv")
survey = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_survey.csv")
visited = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/survey_visited.csv")

In [ ]:
person

In [ ]:
site

In [ ]:
survey

In [ ]:
visited

In [ ]:
site

In [ ]:
# One to one merge
visited_subset = visited.loc[[0, 2, 6]]
visited_subset

In [ ]:
# both the dataframes above have similar content but the content is under different names
# we can merge based on that

# if just do this, merge wont work since we dont have any common column to perform on
one2one_merge = site.merge(visited_subset)
one2one_merge

# Merge error

In [ ]:
one2one_merge = site.merge(visited_subset, left_on = 'name', right_on = 'site')
one2one_merge

In [ ]:
# we can switch as well
one2one_merge = visited_subset.merge(site, left_on = 'site', right_on = 'name')
one2one_merge

In [ ]:
# however, we can use join to get a similar result 
# but with Nan values since site does not have index 6
one2one_join = visited_subset.join(site)
one2one_join

In [ ]:
# since visited_subset only covers [[0,2,6]] -> row 1 shows nan values for visited_subset
one2one_join = site.join(visited_subset) 
one2one_join

In [ ]:
# same data but in site df, its called "name"
# in visited df, its called "site"
Many2One_merge = visited.merge(site, left_on = 'site', right_on = 'name')
Many2One_merge                         

In [ ]:
# Same concept as given above, we just swap the order
One2Many_merge = site.merge(visited, left_on = 'name', right_on = 'site')
One2Many_merge                

In [ ]:
# Manyto Many Merge
enrollment_df = pd.DataFrame({
    'ID' : [1001, 1002],
    'Course' : ["ICCS161", "ICCS161"]
})
enrollment_df

In [ ]:
exam_df = pd.DataFrame({
    "Course": ["ICCS161", "ICCS161"],
    "Exam": ["Midterm", "Final"]
})
exam_df

In [ ]:
Many2Many_merge = enrollment_df.merge(exam_df, left_on = 'Course', right_on = 'Course')
Many2Many_merge                                     

In [ ]:
enrollment_df_2 = pd.DataFrame({
    "ID": [1001, 1002, 1003],
    "Course": ["ICCS161", "ICCS161", "ICCS331"]
})
enrollment_df_2

In [ ]:
# since ICCS331 is not a match in exam_df, it doesnt show up at all
Many2Many_merge_2 = enrollment_df_2.merge(exam_df, left_on = 'Course', right_on = 'Course')
Many2Many_merge_2

In [ ]:
# change the name of the index and merge on that basis
enrollment_df_2.set_index('Course', inplace = True)
enrollment_df_2

In [ ]:
exam_df.set_index('Course', inplace = True)
exam_df

In [ ]:
# since we are using "outer" , even 1003 shows up but just with a Nan value
joiney = enrollment_df_2.join(exam_df, how = 'outer')
joiney                     

In [ ]:
# with inner, only the common values show up
joiney2 = enrollment_df_2.join(exam_df, how = 'inner')
joiney2   

### Conclusion - Similarities and Differences between Concat, Merge, and Join

In [ ]:
df1 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_1.csv")
df2 = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/concat_2.csv")

In [ ]:
df3 = df2.copy()

df3.iloc[2] = df1.iloc[1]
df3.iloc[3] = df1.iloc[2]

df2.columns = ['D', 'E', 'F', 'G']
df3.columns = ['A', 'D', 'G', 'H']

df2.index=[0, 2, 3, 5]
df3.index=[2, 3, 6, 7]

In [ ]:
df1

In [ ]:
df2

In [ ]:
df3

In [ ]:
pd.concat([df1, df2])


In [ ]:
pd.concat([df1, df2], axis =1)

In [ ]:
pd.concat([df1, df2], join = 'inner')

In [ ]:
pd.concat([df1, df2], axis = 1, join = 'inner')

In [ ]:
df1.join(df2, lsuffix="_left", rsuffix="_right", how ='outer')

In [ ]:
pd.merge(df1, df2, left_index=True, right_index=True)

In [ ]:
# based on left - df1 indexes only
df1.join(df2, lsuffix="_left", rsuffix="_right", how='left')

In [ ]:
# based on right - df2 indexes only
df1.join(df2, lsuffix="_left", rsuffix="_right", how ='right')

In [ ]:
pd.merge(df1, df2, left_index=True, right_index=True, how='left')

In [ ]:
pd.merge(df1, df2, left_index=True, right_index=True, how='right')

# Data Prep
- 80% of our work is data prep and 20% analysis
- wide data is more common in data analysis
- long data is easier to visualize

### 5 most common types of Untidy Data
1. column headers are values, not variable names
2. multiples variables in one column
3. variables stored in both rows and columns
4. Multiple types of observational units are stored in the same table.
5. A single observational unit is stored in multiple tables.

In [30]:
# Note: since we are using a data file on the web, we don't need to download it
df_rel = pd.read_csv('https://raw.githubusercontent.com/chendaniely/pydatadc_2018-tidy/master/data/pew.csv')

df_rel

religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k  \
0                  Agnostic     27       34       60       81       76   
1                   Atheist     12       27       37       52       35   
2                  Buddhist     27       21       30       34       33   
3                  Catholic    418      617      732      670      638   
4        Don’t know/refused     15       14       15       11       10   
5          Evangelical Prot    575      869     1064      982      881   
6                     Hindu      1        9        7        9       11   
7   Historically Black Prot    228      244      236      238      197   
8         Jehovah's Witness     20       27       24       24       21   
9                    Jewish     19       19       25       25       30   
10            Mainline Prot    289      495      619      655      651   
11                   Mormon     29       40       48       51       56   
12                   Muslim      6        7        9       10        9   
13                 Orthodox     13       17       23       32       32   
14          Other Christian      9        7       11       13       13   
15             Other Faiths     20       33       40       46       49   
16    Other World Religions      5        2        3        4        2   
17             Unaffiliated    217      299      374      365      341   

    $50-75k  $75-100k  $100-150k  >150k  Don't know/refused  
0       137       122        109     84                  96  
1        70        73         59     74                  76  
2        58        62         39     53                  54  
3      1116       949        792    633                1489  
4        35        21         17     18                 116  
5      1486       949        723    414                1529  
6        34        47         48     54                  37  
7       223       131         81     78                 339  
8        30        15         11      6                  37  
9        95        69         87    151                 162  
10     1107       939        753    634                1328  
11      112        85         49     42                  69  
12       23        16          8      6                  22  
13       47        38         42     46                  73  
14       14        18         14     12                  18  
15       63        46         40     41                  71  
16        7         3          4      4                   8  
17      528       407        321    258                 597

In [31]:
# to get info on the dataset
df_rel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   religion            18 non-null     object
 1   <$10k               18 non-null     int64 
 2   $10-20k             18 non-null     int64 
 3   $20-30k             18 non-null     int64 
 4   $30-40k             18 non-null     int64 
 5   $40-50k             18 non-null     int64 
 6   $50-75k             18 non-null     int64 
 7   $75-100k            18 non-null     int64 
 8   $100-150k           18 non-null     int64 
 9   >150k               18 non-null     int64 
 10  Don't know/refused  18 non-null     int64 
dtypes: int64(10), object(1)
memory usage: 1.7+ KB


In [36]:
test = pd.melt(df_rel,                           # dataset
               id_vars=['religion'],             # list of independent variables
               value_vars=['<$10k', '$10-20k'],  # list of independent variables to melt
               var_name='income',                # name of the new independent variable
               value_name = 'frequency'          # name of the new dependent variable
              )

test

religion   income  frequency
0                  Agnostic    <$10k         27
1                   Atheist    <$10k         12
2                  Buddhist    <$10k         27
3                  Catholic    <$10k        418
4        Don’t know/refused    <$10k         15
5          Evangelical Prot    <$10k        575
6                     Hindu    <$10k          1
7   Historically Black Prot    <$10k        228
8         Jehovah's Witness    <$10k         20
9                    Jewish    <$10k         19
10            Mainline Prot    <$10k        289
11                   Mormon    <$10k         29
12                   Muslim    <$10k          6
13                 Orthodox    <$10k         13
14          Other Christian    <$10k          9
15             Other Faiths    <$10k         20
16    Other World Religions    <$10k          5
17             Unaffiliated    <$10k        217
18                 Agnostic  $10-20k         34
19                  Atheist  $10-20k         27
20                 Buddhist  $10-20k         21
21                 Catholic  $10-20k        617
22       Don’t know/refused  $10-20k         14
23         Evangelical Prot  $10-20k        869
24                    Hindu  $10-20k          9
25  Historically Black Prot  $10-20k        244
26        Jehovah's Witness  $10-20k         27
27                   Jewish  $10-20k         19
28            Mainline Prot  $10-20k        495
29                   Mormon  $10-20k         40
30                   Muslim  $10-20k          7
31                 Orthodox  $10-20k         17
32          Other Christian  $10-20k          7
33             Other Faiths  $10-20k         33
34    Other World Religions  $10-20k          2
35             Unaffiliated  $10-20k        299

In [45]:
df_rel_t = pd.melt(df_rel,
                   id_vars = ['religion'],
                   value_vars = list(df_rel.columns),
                   var_name = 'income',
                   value_name = 'frequency'
                  )

df_rel_t

religion              income  frequency
0                 Agnostic               <$10k         27
1                  Atheist               <$10k         12
2                 Buddhist               <$10k         27
3                 Catholic               <$10k        418
4       Don’t know/refused               <$10k         15
..                     ...                 ...        ...
175               Orthodox  Don't know/refused         73
176        Other Christian  Don't know/refused         18
177           Other Faiths  Don't know/refused         71
178  Other World Religions  Don't know/refused          8
179           Unaffiliated  Don't know/refused        597

[180 rows x 3 columns]

In [46]:
df_rel_t.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   religion   180 non-null    object
 1   income     180 non-null    object
 2   frequency  180 non-null    int64 
dtypes: int64(1), object(2)
memory usage: 4.3+ KB


In [67]:
# let's clean this dataset together
df_tb = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/tb.csv")
df_tb

country  year   m014  m1524   m2534  m3544  m4554  m5564    m65  mu   f014
0      AD  2000    0.0    0.0     1.0    0.0      0      0    0.0 NaN    NaN
1      AE  2000    2.0    4.0     4.0    6.0      5     12   10.0 NaN    3.0
2      AF  2000   52.0  228.0   183.0  149.0    129     94   80.0 NaN   93.0
3      AG  2000    0.0    0.0     0.0    0.0      0      0    1.0 NaN    1.0
4      AL  2000    2.0   19.0    21.0   14.0     24     19   16.0 NaN    3.0
5      AM  2000    2.0  152.0   130.0  131.0     63     26   21.0 NaN    1.0
6      AN  2000    0.0    0.0     1.0    2.0      0      0    0.0 NaN    0.0
7      AO  2000  186.0  999.0  1003.0  912.0    482    312  194.0 NaN  247.0
8      AR  2000   97.0  278.0   594.0  402.0    419    368  330.0 NaN  121.0
9      AS  2000    NaN    NaN     NaN    NaN      1      1    NaN NaN    NaN

In [68]:
# notice how we have a column that has all Nan values

df_tb.drop(['mu'], axis=1, inplace=True)

In [69]:
df_tb.head()

country  year  m014  m1524  m2534  m3544  m4554  m5564   m65  f014
0      AD  2000   0.0    0.0    1.0    0.0      0      0   0.0   NaN
1      AE  2000   2.0    4.0    4.0    6.0      5     12  10.0   3.0
2      AF  2000  52.0  228.0  183.0  149.0    129     94  80.0  93.0
3      AG  2000   0.0    0.0    0.0    0.0      0      0   1.0   1.0
4      AL  2000   2.0   19.0   21.0   14.0     24     19  16.0   3.0

In [70]:
# now, we do melting
df_tb_m = pd.melt(df_tb,
                  id_vars = ['country', 'year'],
                  value_name = 'cases',
                  var_name = 'sex_and_age'
                 )
df_tb_m

country  year sex_and_age  cases
0       AD  2000        m014    0.0
1       AE  2000        m014    2.0
2       AF  2000        m014   52.0
3       AG  2000        m014    0.0
4       AL  2000        m014    2.0
..     ...   ...         ...    ...
75      AM  2000        f014    1.0
76      AN  2000        f014    0.0
77      AO  2000        f014  247.0
78      AR  2000        f014  121.0
79      AS  2000        f014    NaN

[80 rows x 4 columns]

### 1.Split sex and age into two variables: Extract sex, age, lower bound and upper bound group

In [71]:
# extract will create 3 new columns based on our regex 
tmp_df = df_tb_m["sex_and_age"].str.extract("(\D)(\d+)(\d{2})")
tmp_df.iloc[50:60]

0   1   2
50  m  55  64
51  m  55  64
52  m  55  64
53  m  55  64
54  m  55  64
55  m  55  64
56  m  55  64
57  m  55  64
58  m  55  64
59  m  55  64

### 2. Name the columns accordingly

In [72]:
tmp_df.columns = ['sex', 'age_lower', 'age_upper']
tmp_df

sex age_lower age_upper
0    m         0        14
1    m         0        14
2    m         0        14
3    m         0        14
4    m         0        14
..  ..       ...       ...
75   f         0        14
76   f         0        14
77   f         0        14
78   f         0        14
79   f         0        14

[80 rows x 3 columns]

### 3. Create age column based on age-lower and age-upper

In [73]:
tmp_df['age'] = tmp_df['age_lower'] + '-' + tmp_df['age_upper']
tmp_df

sex age_lower age_upper   age
0    m         0        14  0-14
1    m         0        14  0-14
2    m         0        14  0-14
3    m         0        14  0-14
4    m         0        14  0-14
..  ..       ...       ...   ...
75   f         0        14  0-14
76   f         0        14  0-14
77   f         0        14  0-14
78   f         0        14  0-14
79   f         0        14  0-14

[80 rows x 4 columns]

In [76]:
df_tb_m = pd.concat([df_tb_m, tmp_df], axis=1)
df_tb_m

country  year sex_and_age  cases sex age_lower age_upper   age
0       AD  2000        m014    0.0   m         0        14  0-14
1       AE  2000        m014    2.0   m         0        14  0-14
2       AF  2000        m014   52.0   m         0        14  0-14
3       AG  2000        m014    0.0   m         0        14  0-14
4       AL  2000        m014    2.0   m         0        14  0-14
..     ...   ...         ...    ...  ..       ...       ...   ...
75      AM  2000        f014    1.0   f         0        14  0-14
76      AN  2000        f014    0.0   f         0        14  0-14
77      AO  2000        f014  247.0   f         0        14  0-14
78      AR  2000        f014  121.0   f         0        14  0-14
79      AS  2000        f014    NaN   f         0        14  0-14

[80 rows x 8 columns]

### 4. Drop unnecessary columns and rows

In [79]:
df_tb_m = df_tb_m.drop(['sex_and_age', 'age_lower', 'age_upper'], axis=1)
df_tb_m = df_tb_m.dropna()
df_tb_m                    

country  year  cases sex   age
0       AD  2000    0.0   m  0-14
1       AE  2000    2.0   m  0-14
2       AF  2000   52.0   m  0-14
3       AG  2000    0.0   m  0-14
4       AL  2000    2.0   m  0-14
..     ...   ...    ...  ..   ...
74      AL  2000    3.0   f  0-14
75      AM  2000    1.0   f  0-14
76      AN  2000    0.0   f  0-14
77      AO  2000  247.0   f  0-14
78      AR  2000  121.0   f  0-14

[64 rows x 5 columns]

In [80]:
df_tb_m = df_tb_m.astype({'cases':'int'})
df_tb_m

country  year  cases sex   age
0       AD  2000      0   m  0-14
1       AE  2000      2   m  0-14
2       AF  2000     52   m  0-14
3       AG  2000      0   m  0-14
4       AL  2000      2   m  0-14
..     ...   ...    ...  ..   ...
74      AL  2000      3   f  0-14
75      AM  2000      1   f  0-14
76      AN  2000      0   f  0-14
77      AO  2000    247   f  0-14
78      AR  2000    121   f  0-14

[64 rows x 5 columns]

### Now, the data looks tidy

In [ ]:
df_bill = pd.read_csv("/Users/srisuphachawla/Documents/DataScienceDownloads/billboard.csv")
df_bill